#INCLUDE 'PROTHEUS.CH'
#INCLUDE 'TOTVS.CH'

/*/{Protheus.doc} MTA010MNU
@author Gabriel Rossi Mafioletti
@since 11/05/2017
@version 1.0
@description Ponto de Entrada Para inclusão de itens no 
				menu ações relacionadas do cadastro de produtos.
@type function
/*/

User Function MTA010MNU()

	aAdd(aRotina,{ "Alterar Peso" 					, 'U_BIAFG003'	, 0, 6,0,nil}) 	  		//Alterar Peso
	aAdd(aRotina,{ "Filtrar Marca/Part.Num" 		, 'U_PDMFISB1'	, 0, 6,0,nil}) 	  		//Filtro de Marca/PN na tabela ZD6

Return