#include "totvs.ch"

static oData as object

class cacheData

    static method get()
    static method set()    
    static method clear()

end class

static method set(uSection,uPropertyKey,uValue) class cacheData
    DEFAULT oData:=tHash():New()
    return(oData:SetPropertyValue(uSection,uPropertyKey,uValue))

static method get(uSection,uPropertyKey,uDefaultValue) class cacheData
    DEFAULT oData:=tHash():New()
    return(oData:GetPropertyValue(uSection,uPropertyKey,uDefaultValue)) 

static method clear() class cacheData
    DEFAULT oData:=tHash():New()
    return(oData:Clear())
