USE [P11]
GO
/****** Object:  StoredProcedure [dbo].[STPCAC_ORDENS_DE_SERVICO]    Script Date: 08/05/2015 13:52:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STPCAC_ORDENS_DE_SERVICO] @DT_DE VARCHAR(8),@DT_ATE VARCHAR(8),@TIPO INT, @FECHADAS BIT
AS BEGIN
SELECT AB7_NUMOS NUMOS,
		AB6.AB6_EMISSA EMISS, 
		AB7_CODCLI CODCLI, 
		SA1.A1_NOME NOMCLI, 
		AB7.AB7_YNRFOR NRFORM,
		AB7.AB7_MEMO1 CDMEMO,
		ISNULL(AA1.AA1_NOMTEC,'') AS NOMTEC,
		ISNULL(AB8.AB8_ENTREG,'') AS DTAPON,
		ISNULL(AB8.AB8_CODPRO,'') AS CODPRO,
		ISNULL(AB8.AB8_DESPRO,'') AS DESPRO,
		AB7.AB7_YRETRA AS RETRAB
FROM AB6010 AB6
JOIN SA1010 SA1
ON SA1.A1_FILIAL = ''
AND AB6.AB6_CODCLI = SA1.A1_COD
AND AB6.AB6_LOJA = SA1.A1_LOJA
AND SA1.D_E_L_E_T_ = ''
JOIN AB7010 AB7
ON AB7.AB7_FILIAL = AB6.AB6_FILIAL
AND AB7.AB7_NUMOS = AB6.AB6_NUMOS
AND AB7.AB7_CODCLI = AB6.AB6_CODCLI
AND AB7.AB7_LOJA = AB6.AB6_LOJA
AND (
		(@FECHADAS = 'TRUE' 
			AND AB7.AB7_TIPO IN ('2','4')
		)
	OR
		(@FECHADAS = 'FALSE' 
			AND AB7.AB7_TIPO IN ('1','2','3','4','5')
		)
	)
AND AB7.D_E_L_E_T_ = ''
LEFT JOIN AB8010 AB8
ON AB8.AB8_FILIAL = AB7.AB7_FILIAL
AND AB8.AB8_NUMOS = AB7.AB7_NUMOS
AND AB8.AB8_ITEM = AB7.AB7_ITEM
AND AB8.AB8_CODCLI = AB7_CODCLI
AND AB8.D_E_L_E_T_ = ''
LEFT JOIN AA1010 AA1
ON AA1.AA1_CODTEC = AB6.AB6_YCODTE
AND AA1.D_E_L_E_T_ = ''
WHERE AB6.D_E_L_E_T_ = '' 
AND AB6.AB6_EMISSA BETWEEN @DT_DE AND @DT_ATE
 AND (
		(
			@TIPO IN (1,3) AND ( 
										EXISTS(SELECT 1 FROM AB8010 AB8 WHERE AB8.AB8_FILIAL = AB6_FILIAL AND AB8.AB8_NUMOS = AB6.AB6_NUMOS AND AB8.AB8_CODSER <> '000005' AND AB8.D_E_L_E_T_ = '') OR
										NOT EXISTS(SELECT 1 FROM AB8010 AB8 WHERE AB8.AB8_FILIAL = AB6_FILIAL AND AB8.AB8_NUMOS = AB6.AB6_NUMOS AND AB8.D_E_L_E_T_ = '')
									) 
		) 
		OR (
		
			@TIPO IN (2,3) 
			AND EXISTS(SELECT 1 FROM AB8010 AB8 WHERE AB8.AB8_FILIAL = AB6_FILIAL AND AB8.AB8_NUMOS = AB6.AB6_NUMOS AND AB8.AB8_CODSER = '000005' AND AB8.D_E_L_E_T_ = '') 
										 
			)
	)
ORDER BY AB7_CODCLI,AB7_NUMOS,AB6.AB6_EMISSA

END
