#INCLUDE "RWMAKE.CH"
#INCLUDE "TOPCONN.CH"
#INCLUDE "TBICONN.CH"'

/*/{Protheus.doc} WORK_TRAN
@author Bruno Madaleno
@since 28/10/2008
@version 1.0
@description  Workflow responsavel em enviar todos os pedidos em romaneio que se encontram em aberto ate a data de entrega C6_ENTRE <= DTB
@obs Retirado funcao fUpdSC63. O campo C6_YSTAT esta gravado atraves de job SQL
@obs Ticket 22844 - Tratar travamentos
@type function
/*/

User Function WORK_TRAN()
	Local xv_Emps := U_BAGtEmpr("01_05_13") 
	Local x

	For x := 1 to Len(xv_Emps)

		//Inicializa o ambiente
		RPCSetType(3)

		WfPrepEnv(xv_Emps[x,1], xv_Emps[x,2])

		ConOut("HORA: "+TIME()+" - GERANDO WORKFLOW DAS TRANSPORTADORAS " + xv_Emps[x,1])

		Processa({|| WORK_TRAN() })

		ConOut("HORA: "+TIME()+" - FIM DO WORKFLOW DAS TRANSPORTADORAS " + xv_Emps[x,1])

		//Finaliza o ambiente criado
		RpcClearEnv()

	Next

Return()

//--------------------------------------------------------------------------
//EXECUTA FUNCAO QUE GERA E ENVIA OS RELAT”RIOS
//--------------------------------------------------------------------------
Static Function WORK_TRAN()
	Private ENTER	:= CHR(13)+CHR(10)
	Private CEMAIL := ""
	Private C_HTML := ""
	Private LOK	:= .F.
	Private CSQL := ""

	Private CCC_TEXTO	:= ""
	Private lDebugWF := .F.
	Private dEmails := ""

	//Nome temporario para as tabelas
	nNomeSC5	:= "TMPRAC_WORK_TRAN_SC5"+cEmpAnt+__cUserID+strzero(seconds()*3500,10) 
	nNomeSC6	:= "TMPRAC_WORK_TRAN_SC6"+cEmpAnt+__cUserID+strzero(seconds()*3500,10)//Alltrim(Str(randomize(1,34000)))
	nNomeSC9	:= "TMPRAC_WORK_TRAN_SC9"+cEmpAnt+__cUserID+strzero(seconds()*3500,10)//strzero(seconds()*3500,10)
	nNomeSE1	:= ""
	aRet		:= {}

	//GERA VIEW DA TABELA SC9
	cSql := ""
	// Tiago Rossini Coradini - 01/08/16 - OS: 2813-16 - Claudeir Fadini - Ajuste no filtro de produtos por marca
	cSql += "SELECT TMP.*, ZZ7.ZZ7_EMP AS MARCA "+ Enter 
	cSql += "INTO "+nNomeSC9+" FROM (" + Enter	
	cSql += "SELECT '"+cEmpAnt+"' AS 'EMPRESA', C9_FILIAL,C9_PEDIDO,C9_AGREG,C9_PRODUTO,C9_LOTECTL,C9_CLIENTE,C9_LOJA,C9_ITEM,C9_NFISCAL,C9_BLEST,C9_BLCRED,C9_GRUPO,C9_LOCAL,C9_DATALIB,C9_QTDLIB,C9_QTDLIB2,C9_YRASTAT " + Enter
	cSql += "FROM "+RetSqlName("SC9")+" WITH (NOLOCK) " + Enter

	If GETMV("MV_YVLDRA")
		cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND D_E_L_E_T_ = '' " + Enter
	Else
		cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND C9_YRASTAT <> '2' AND D_E_L_E_T_ = '' " + Enter
	EndIf

	If cEmpAnt == "01"
		cSql += "UNION ALL " + Enter
		cSql += "SELECT '05' AS 'EMPRESA', C9_FILIAL,C9_PEDIDO,C9_AGREG,C9_PRODUTO,C9_LOTECTL,C9_CLIENTE,C9_LOJA,C9_ITEM,C9_NFISCAL,C9_BLEST,C9_BLCRED,C9_GRUPO,C9_LOCAL,C9_DATALIB,C9_QTDLIB,C9_QTDLIB2,C9_YRASTAT " + Enter	
		cSql += "FROM SC9050 WITH (NOLOCK) " + Enter

		If GETMV("MV_YVLDRA")
			cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND D_E_L_E_T_ = '' " + Enter
		Else
			cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND C9_YRASTAT <> '2' AND D_E_L_E_T_ = '' " + Enter
		EndIf

	EndIf

	// Tiago Rossini Coradini - 26/10/16 - OS: 3997-16 - Ana Paula e 3998-16 - Caio Dias - Ajuste no filtro para buscar produtos de Porcelanato Incesa
	If cEmpAnt == "05"
		cSql += "UNION ALL " + Enter
		cSql += "SELECT '01' AS 'EMPRESA', C9_FILIAL,C9_PEDIDO,C9_AGREG,C9_PRODUTO,C9_LOTECTL,C9_CLIENTE,C9_LOJA,C9_ITEM,C9_NFISCAL,C9_BLEST,C9_BLCRED,C9_GRUPO,C9_LOCAL,C9_DATALIB,C9_QTDLIB,C9_QTDLIB2,C9_YRASTAT " + Enter	
		cSql += "FROM SC9010 WITH (NOLOCK) " + Enter

		If GETMV("MV_YVLDRA")
			cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND D_E_L_E_T_ = '' " + Enter
		Else
			cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND C9_YRASTAT <> '2' AND D_E_L_E_T_ = '' " + Enter
		EndIf

	EndIf

	If cEmpAnt $ "01_05"
		cSql += "UNION ALL " + Enter
		cSql += "SELECT '13' AS 'EMPRESA', C9_FILIAL,C9_PEDIDO,C9_AGREG,C9_PRODUTO,C9_LOTECTL,C9_CLIENTE,C9_LOJA,C9_ITEM,C9_NFISCAL,C9_BLEST,C9_BLCRED,C9_GRUPO,C9_LOCAL,C9_DATALIB,C9_QTDLIB,C9_QTDLIB2,C9_YRASTAT " + Enter	
		cSql += "FROM SC9130 WITH (NOLOCK) " + Enter

		If GETMV("MV_YVLDRA")
			cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND D_E_L_E_T_ = '' " + Enter
		Else
			cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND C9_YRASTAT <> '2' AND D_E_L_E_T_ = '' " + Enter
		EndIf

		//RUBENS JUNIOR (FACILE SISTEMAS) OS: 0516-14 DATA: 09/05/14                                                                              
		cSql += "UNION ALL " + Enter
		cSql += "SELECT '14' AS 'EMPRESA', C9_FILIAL,C9_PEDIDO,C9_AGREG,C9_PRODUTO,C9_LOTECTL,C9_CLIENTE,C9_LOJA,C9_ITEM,C9_NFISCAL,C9_BLEST,C9_BLCRED,C9_GRUPO,C9_LOCAL,C9_DATALIB,C9_QTDLIB,C9_QTDLIB2,C9_YRASTAT " + Enter
		cSql += "FROM SC9140 WITH (NOLOCK) " + Enter

		If GETMV("MV_YVLDRA")
			cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_CLIENTE <> '000481' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND D_E_L_E_T_ = '' " + Enter		
		Else
			cSql += "WHERE C9_FILIAL = '"+xFilial("SC9")+"' AND C9_CLIENTE <> '000481' AND C9_NFISCAL = '' AND C9_BLEST = '' AND C9_BLCRED = '' AND C9_YRASTAT <> '2' AND D_E_L_E_T_ = '' " + Enter		
		EndIf

	EndIf

	cSql += " ) AS TMP " + Enter

	// Tiago Rossini Coradini - 02/07/16 - OS: 2813-16 - Claudeir Fadini - Ajuste no filtro de produtos por marca 
	cSql += " INNER JOIN SB1010 SB1 WITH (NOLOCK) " 
	cSql += "	ON C9_PRODUTO = B1_COD "
	cSql += "	AND B1_YLINHA <> '0000' "
	cSql += "	AND SB1.D_E_L_E_T_ = '' "

	// Tiago Rossini Coradini - 26/10/16 - OS: 3997-16 - Ana Paula e 3998-16 - Caio Dias - Ajuste no filtro para buscar produtos de Porcelanato Incesa	
	cSql += "	INNER JOIN ZZ7010 ZZ7 WITH (NOLOCK) "
	cSql += "	ON B1_YLINHA = ZZ7_COD "
	cSql += "	AND B1_YLINSEQ = ZZ7_LINSEQ "
	cSql += "	AND SUBSTRING(ZZ7_EMP,1,2) = " + cEmpAnt
	//cSql += "	AND ZZ7_EMP " + If (cEmpAnt == "01", "=", "<>") + ValToSQL("0101")	        
	cSql += "	AND ZZ7.D_E_L_E_T_ = '' "

	// Tiago Rossini Coradini - 11/10/16 - OS: 3605-16 - Anderson MendonÁa - Ajuste no filtro de produtos para buscar produtos do grupo 216
	cSql += "UNION ALL "

	cSql += " SELECT "+ ValToSQL(cEmpAnt) +" AS 'EMPRESA', C9_FILIAL, C9_PEDIDO, C9_AGREG, C9_PRODUTO, C9_LOTECTL, C9_CLIENTE, C9_LOJA, "
	cSql += " C9_ITEM, C9_NFISCAL, C9_BLEST, C9_BLCRED, C9_GRUPO, C9_LOCAL, C9_DATALIB, C9_QTDLIB, C9_QTDLIB2, C9_YRASTAT, "
	cSql += ValToSQL(cEmpAnt+cFilAnt) + " AS ZZ7_EMP "
	cSql += " FROM "+ RetSqlName("SC9") +" WITH (NOLOCK) "
	cSql += " WHERE C9_FILIAL = " + ValToSQL(xFilial("SC9"))
	cSql += " AND C9_NFISCAL = '' "
	cSql += " AND C9_BLEST = '' "
	cSql += " AND C9_BLCRED = '' "

	If !GetMV("MV_YVLDRA")
		cSql += " AND C9_YRASTAT <> '2' "
	EndIf

	cSql += " AND (SUBSTRING(C9_GRUPO,1,3) = '216' AND C9_LOCAL = '05') "
	cSql += " AND D_E_L_E_T_ = '' "

	TcSQLExec(cSql)                                                                         

	//GERA VIEW DA TABELA SC5    
	cSql := ""                   
	cSql += ";WITH SC5_07 AS " + Enter 
	cSql += "(SELECT DISTINCT C5_NUM, C5_CLIENTE, C5_LOJACLI, C5_YSUBTP, C5_YAPROV, C5_TRANSP, C5_VEND1, C5_VEND2, C5_YPEDORI, C5_YEMPPED  " + Enter
	cSql += "		, C5_YFLAG, C5_YEND, C5_YBAIRRO, C5_YMUN, C5_YEST, C5_YCEP, C5_YTEL	" + Enter
	cSql += "FROM SC5070 SC5 WITH (NOLOCK) INNER JOIN SC6070 SC6 WITH (NOLOCK) ON	" + Enter
	cSql += "     C5_NUM = C6_NUM  						" + Enter
	cSql += "WHERE C5_FILIAL = '01' 		AND			" + Enter
	cSql += "      C6_FILIAL = '01' 		AND 		" + Enter
	cSql += "	   C6_QTDVEN-C6_QTDENT > 0	AND 		" + Enter
	cSql += "      C6_BLQ <> 'R' 			AND			" + Enter
	cSql += "      SC5.D_E_L_E_T_ = '' 		AND			" + Enter
	cSql += "      SC6.D_E_L_E_T_ = ''					" + Enter
	cSql += ")	" + Enter
	cSql += "	" + Enter
	cSql += "SELECT TMP.EMPRESA, TMP.C5_FILIAL, TMP.C5_NUM, TMP.C5_TIPO, TMP.C5_YEMP, TMP.C5_YLINHA, TMP.C5_CLIENTE, TMP.C5_LOJAENT, TMP.C5_LOJACLI, TMP.C5_YRECR, ISNULL(LC5.C5_YSUBTP, TMP.C5_YSUBTP) AS C5_YSUBTP, " + Enter
	cSql += "	ISNULL(LC5.C5_TRANSP, TMP.C5_TRANSP) AS C5_TRANSP,	TMP.C5_TIPOCLI,	TMP.C5_CONDPAG,	TMP.C5_YFORMA,	TMP.C5_YMAXCND,	TMP.C5_YPERC,	TMP.C5_YPRZINC,	TMP.C5_YDTINC,	TMP.C5_YPC,	TMP.C5_VLRFRET,	TMP.C5_YVLRREV,	" + Enter
	cSql += "	TMP.C5_YCLIDEL,	TMP.C5_YPERDEL,	TMP.C5_YBAIDEL,	TMP.C5_YNFDEL,	TMP.C5_TABELA,	ISNULL(LC5.C5_VEND1, TMP.C5_VEND1) AS C5_VEND1,	TMP.C5_COMIS1,	ISNULL(LC5.C5_VEND2, TMP.C5_VEND2) AS C5_VEND2,	TMP.C5_COMIS2,	" + Enter
	cSql += "	TMP.C5_VEND3,	TMP.C5_COMIS3,	TMP.C5_VEND4,	TMP.C5_COMIS4,	TMP.C5_VEND5,	TMP.C5_COMIS5,	TMP.C5_DESC1,	TMP.C5_DESC2,	TMP.C5_DESC3,	TMP.C5_DESC4,	TMP.C5_BANCO,	TMP.C5_DESCFI,	TMP.C5_EMISSAO,	" + Enter
	cSql += "	TMP.C5_COTACAO,	TMP.C5_PARC1,	TMP.C5_DATA1,	TMP.C5_PARC2,	TMP.C5_DATA2,	TMP.C5_PARC3,	TMP.C5_DATA3,	TMP.C5_PARC4,	TMP.C5_DATA4,	TMP.C5_TPFRETE,	TMP.C5_FRETE,	TMP.C5_SEGURO,	TMP.C5_DESPESA,	" + Enter
	cSql += "	TMP.C5_FRETAUT,	TMP.C5_REAJUST,	TMP.C5_MOEDA,	TMP.C5_PESOL,	TMP.C5_PBRUTO,	TMP.C5_REIMP,	TMP.C5_REDESP,	TMP.C5_VOLUME1,	TMP.C5_VOLUME2,	TMP.C5_VOLUME3,	TMP.C5_VOLUME4,	TMP.C5_ESPECI1,	TMP.C5_ESPECI2,	" + Enter
	cSql += "	TMP.C5_ESPECI3,	TMP.C5_ESPECI4,	TMP.C5_ACRSFIN,	TMP.C5_MENNOTA,	TMP.C5_MENPAD,	TMP.C5_INCISS,	TMP.C5_LIBEROK,	TMP.C5_OK,	TMP.C5_NOTA,	TMP.C5_SERIE,	TMP.C5_VENDA,	TMP.C5_KITREP,	TMP.C5_TIPLIB,	TMP.C5_OS,	" + Enter
	cSql += "	TMP.C5_YMARCA,	TMP.C5_YNUMERO,	TMP.C5_DESCONT,	TMP.C5_PEDEXP,	TMP.C5_TXMOEDA,	TMP.C5_USERLGI,	TMP.C5_USERLGA,	TMP.C5_YAAPROV,	ISNULL(LC5.C5_YAPROV, TMP.C5_YAPROV) AS C5_YAPROV ,	TMP.C5_YDIGP,	TMP.C5_YALTP,	" + Enter
	cSql += "	TMP.C5_TPCARGA,	TMP.C5_PREPEMB,	TMP.C5_CLIENT,	TMP.C5_PDESCAB,	ISNULL(LC5.C5_YFLAG,TMP.C5_YFLAG) AS C5_YFLAG,	ISNULL(LC5.C5_YEND,TMP.C5_YEND) C5_YEND, ISNULL(LC5.C5_YEST,TMP.C5_YEST) C5_YEST,ISNULL(LC5.C5_YMUN,TMP.C5_YMUN) C5_YMUN," + Enter
	cSql += "	ISNULL(LC5.C5_YBAIRRO,TMP.C5_YBAIRRO) C5_YBAIRRO,	ISNULL(LC5.C5_YCEP,TMP.C5_YCEP)C5_YCEP,	ISNULL(LC5.C5_YTEL,TMP.C5_YTEL) C5_YTEL,	TMP.C5_YFATOR,	TMP.C5_YDESCLI,	" + Enter
	cSql += "	TMP.C5_RECISS,	TMP.D_E_L_E_T_,	TMP.R_E_C_N_O_,	TMP.R_E_C_D_E_L_,	TMP.C5_BLQ,	TMP.C5_FORNISS,	TMP.C5_CONTRA,	TMP.C5_VLR_FRT,	TMP.C5_YCC,	TMP.C5_YVLTOTP,	TMP.C5_YTPBLQ,	TMP.C5_YPEDPAI,	TMP.C5_YMEDDES,	" + Enter
	cSql += "	TMP.C5_YMDESPD, TMP.C5_YPEDORI, TMP.C5_YITEMCT, TMP.C5_YCLVL, TMP.C5_YSI, TMP.C5_YCLIORI, TMP.C5_YLOJORI, TMP.C5_YCODMUN	" + Enter
	cSql += "INTO "+nNomeSC5+" FROM (" + Enter
	cSql += "SELECT '"+cEmpAnt+"' AS 'EMPRESA' , C5_FILIAL,	C5_NUM,	C5_TIPO, C5_YEMP, C5_YLINHA,	C5_CLIENTE,	C5_LOJAENT,	C5_LOJACLI,	C5_YRECR,	C5_YSUBTP,	C5_TRANSP,	C5_TIPOCLI,	C5_CONDPAG,	C5_YFORMA,	C5_YMAXCND,	" + Enter
	cSql += "	C5_YPERC,	C5_YPRZINC,	C5_YDTINC,	C5_YPC,	C5_VLRFRET,	C5_YVLRREV,	C5_YCLIDEL,	C5_YPERDEL,	C5_YBAIDEL,	C5_YNFDEL,	C5_TABELA,	C5_VEND1,	C5_COMIS1,	C5_VEND2,	C5_COMIS2,	C5_VEND3,	C5_COMIS3,	C5_VEND4,	C5_COMIS4,	" + Enter
	cSql += "	C5_VEND5,	C5_COMIS5,	C5_DESC1,	C5_DESC2,	C5_DESC3,	C5_DESC4,	C5_BANCO,	C5_DESCFI,	C5_EMISSAO,	C5_COTACAO,	C5_PARC1,	C5_DATA1,	C5_PARC2,	C5_DATA2,	C5_PARC3,	C5_DATA3,	C5_PARC4,	C5_DATA4,	" + Enter
	cSql += "	C5_TPFRETE,	C5_FRETE,	C5_SEGURO,	C5_DESPESA,	C5_FRETAUT,	C5_REAJUST,	C5_MOEDA,	C5_PESOL,	C5_PBRUTO,	C5_REIMP,	C5_REDESP,	C5_VOLUME1,	C5_VOLUME2,	C5_VOLUME3,	C5_VOLUME4,	C5_ESPECI1,	C5_ESPECI2,	C5_ESPECI3,	" + Enter
	cSql += "	C5_ESPECI4,	C5_ACRSFIN,	C5_MENNOTA,	C5_MENPAD,	C5_INCISS,	C5_LIBEROK,	C5_OK,	C5_NOTA,	C5_SERIE,	C5_VENDA,	C5_KITREP,	C5_TIPLIB,	C5_OS,	C5_YMARCA,	C5_YNUMERO,	C5_DESCONT,	C5_PEDEXP,	C5_TXMOEDA,	C5_USERLGI,	" + Enter
	cSql += "	C5_USERLGA,	C5_YAAPROV,	C5_YAPROV,	C5_YDIGP,	C5_YALTP,	C5_YOBS,	C5_TPCARGA,	C5_PREPEMB,	C5_CLIENT,	C5_PDESCAB,	C5_YFLAG,	C5_YEND,	C5_YEST,	C5_YMUN,	C5_YBAIRRO,	C5_YCEP,	C5_YTEL,	C5_YFATOR,	C5_YDESCLI,	" + Enter
	cSql += "	C5_RECISS,	D_E_L_E_T_,	R_E_C_N_O_,	R_E_C_D_E_L_,	C5_BLQ,	C5_FORNISS,	C5_CONTRA,	C5_VLR_FRT,	C5_YCC,	C5_YVLTOTP,	C5_YTPBLQ,	C5_YPEDPAI,	C5_YMEDDES,	C5_YMDESPD, C5_YPEDORI, C5_YITEMCT, C5_YCLVL, C5_YSI, C5_YCLIORI, C5_YLOJORI, C5_YCODMUN,	" + Enter
	cSql += " CLI_ORIG = CASE WHEN C5_YCLIORI <> '' THEN C5_YCLIORI ELSE C5_CLIENTE END, "+ Enter
	cSql += " LOJ_ORIG = CASE WHEN C5_YLOJORI <> '' THEN C5_YLOJORI ELSE C5_LOJACLI END "+ Enter
	cSql += "FROM "+RetSqlName("SC5")+" WITH (NOLOCK) " + Enter
	cSql += "WHERE C5_FILIAL = '"+xFilial("SC5")+"' AND C5_NUM IN (SELECT C9_PEDIDO FROM "+nNomeSC9+" WHERE EMPRESA = '"+cEmpAnt+"') AND D_E_L_E_T_ = ''	" + Enter

	If cEmpAnt == "01"
		cSql += "UNION ALL	" + Enter
		cSql += "SELECT '05' AS 'EMPRESA' , C5_FILIAL,	C5_NUM,	C5_TIPO, C5_YEMP, C5_YLINHA,	C5_CLIENTE,	C5_LOJAENT,	C5_LOJACLI,	C5_YRECR,	C5_YSUBTP,	C5_TRANSP,	C5_TIPOCLI,	C5_CONDPAG,	C5_YFORMA,	C5_YMAXCND,	C5_YPERC,	"+ Enter
		cSql += "	C5_YPRZINC,	C5_YDTINC,	C5_YPC,	C5_VLRFRET,	C5_YVLRREV,	C5_YCLIDEL,	C5_YPERDEL,	C5_YBAIDEL,	C5_YNFDEL,	C5_TABELA,	C5_VEND1,	C5_COMIS1,	C5_VEND2,	C5_COMIS2,	C5_VEND3,	C5_COMIS3,	C5_VEND4,	C5_COMIS4,	C5_VEND5,	"+ Enter
		cSql += "	C5_COMIS5,	C5_DESC1,	C5_DESC2,	C5_DESC3,	C5_DESC4,	C5_BANCO,	C5_DESCFI,	C5_EMISSAO,	C5_COTACAO,	C5_PARC1,	C5_DATA1,	C5_PARC2,	C5_DATA2,	C5_PARC3,	C5_DATA3,	C5_PARC4,	C5_DATA4,	C5_TPFRETE,	C5_FRETE,	"+ Enter
		cSql += "	C5_SEGURO,	C5_DESPESA,	C5_FRETAUT,	C5_REAJUST,	C5_MOEDA,	C5_PESOL,	C5_PBRUTO, C5_REIMP,	C5_REDESP,	C5_VOLUME1,	C5_VOLUME2,	C5_VOLUME3,	C5_VOLUME4,	C5_ESPECI1,	C5_ESPECI2,	C5_ESPECI3,	C5_ESPECI4,	C5_ACRSFIN,	C5_MENNOTA,	"+ Enter
		cSql += "	C5_MENPAD,	C5_INCISS,	C5_LIBEROK,	C5_OK,	C5_NOTA,	C5_SERIE,	C5_VENDA,	C5_KITREP,	C5_TIPLIB,	C5_OS,	C5_YMARCA,	C5_YNUMERO,	C5_DESCONT,	C5_PEDEXP,	C5_TXMOEDA,	C5_USERLGI,	C5_USERLGA,	C5_YAAPROV,	C5_YAPROV,	C5_YDIGP,	"+ Enter
		cSql += "	C5_YALTP,	C5_YOBS,	C5_TPCARGA,	C5_PREPEMB,	C5_CLIENT,	C5_PDESCAB,	C5_YFLAG,	C5_YEND,	C5_YEST,	C5_YMUN,	C5_YBAIRRO,	C5_YCEP,	C5_YTEL,	C5_YFATOR,	C5_YDESCLI,	C5_RECISS,	D_E_L_E_T_,	R_E_C_N_O_,	R_E_C_D_E_L_,	"+ Enter
		cSql += "	C5_BLQ,	C5_FORNISS,	C5_CONTRA,	C5_VLR_FRT,	C5_YCC,	C5_YVLTOTP,	C5_YTPBLQ,	C5_YPEDPAI,	C5_YMEDDES,	C5_YMDESPD, C5_YPEDORI, C5_YITEMCT, C5_YCLVL, C5_YSI, C5_YCLIORI, C5_YLOJORI, C5_YCODMUN,	" + Enter
		cSql += " CLI_ORIG = CASE WHEN C5_YCLIORI <> '' THEN C5_YCLIORI ELSE C5_CLIENTE END, "+ Enter
		cSql += " LOJ_ORIG = CASE WHEN C5_YLOJORI <> '' THEN C5_YLOJORI ELSE C5_LOJACLI END "+ Enter
		cSql += "FROM SC5050 WITH (NOLOCK) " + Enter
		cSql += "WHERE C5_FILIAL = '"+xFilial("SC5")+"' AND C5_NUM IN (SELECT C9_PEDIDO FROM "+nNomeSC9+" WHERE EMPRESA = '05') AND D_E_L_E_T_ = ''	" + Enter
	EndIf

	If cEmpAnt $ "01_05"

		If cEmpAnt == "05"

			cSql += "UNION ALL	" + Enter
			cSql += "SELECT '01' AS 'EMPRESA' , C5_FILIAL,	C5_NUM,	C5_TIPO, C5_YEMP, C5_YLINHA,	C5_CLIENTE,	C5_LOJAENT,	C5_LOJACLI,	C5_YRECR,	C5_YSUBTP,	C5_TRANSP,	C5_TIPOCLI,	C5_CONDPAG,	C5_YFORMA,	C5_YMAXCND,	C5_YPERC,	" + Enter
			cSql += "	C5_YPRZINC,	C5_YDTINC,	C5_YPC,	C5_VLRFRET,	C5_YVLRREV,	C5_YCLIDEL,	C5_YPERDEL,	C5_YBAIDEL,	C5_YNFDEL,	C5_TABELA,	C5_VEND1,	C5_COMIS1,	C5_VEND2,	C5_COMIS2,	C5_VEND3,	C5_COMIS3,	C5_VEND4,	C5_COMIS4,	C5_VEND5,	" + Enter
			cSql += "	C5_COMIS5,	C5_DESC1,	C5_DESC2,	C5_DESC3,	C5_DESC4,	C5_BANCO,	C5_DESCFI,	C5_EMISSAO,	C5_COTACAO,	C5_PARC1,	C5_DATA1,	C5_PARC2,	C5_DATA2,	C5_PARC3,	C5_DATA3,	C5_PARC4,	C5_DATA4,	C5_TPFRETE,	C5_FRETE,	" + Enter
			cSql += "	C5_SEGURO,	C5_DESPESA,	C5_FRETAUT,	C5_REAJUST,	C5_MOEDA,	C5_PESOL,	C5_PBRUTO, C5_REIMP,	C5_REDESP,	C5_VOLUME1,	C5_VOLUME2,	C5_VOLUME3,	C5_VOLUME4,	C5_ESPECI1,	C5_ESPECI2,	C5_ESPECI3,	C5_ESPECI4,	C5_ACRSFIN,	C5_MENNOTA,	" + Enter
			cSql += "	C5_MENPAD,	C5_INCISS,	C5_LIBEROK,	C5_OK,	C5_NOTA,	C5_SERIE,	C5_VENDA,	C5_KITREP,	C5_TIPLIB,	C5_OS,	C5_YMARCA,	C5_YNUMERO,	C5_DESCONT,	C5_PEDEXP,	C5_TXMOEDA,	C5_USERLGI,	C5_USERLGA,	C5_YAAPROV,	C5_YAPROV,	C5_YDIGP,	" + Enter
			cSql += "	C5_YALTP,	C5_YOBS,	C5_TPCARGA,	C5_PREPEMB,	C5_CLIENT,	C5_PDESCAB,	C5_YFLAG,	C5_YEND,	C5_YEST,	C5_YMUN,	C5_YBAIRRO,	C5_YCEP,	C5_YTEL,	C5_YFATOR,	C5_YDESCLI,	C5_RECISS,	D_E_L_E_T_,	R_E_C_N_O_,	R_E_C_D_E_L_,	" + Enter
			cSql += "	C5_BLQ,	C5_FORNISS,	C5_CONTRA,	C5_VLR_FRT,	C5_YCC,	C5_YVLTOTP,	C5_YTPBLQ,	C5_YPEDPAI,	C5_YMEDDES,	C5_YMDESPD, C5_YPEDORI, C5_YITEMCT, C5_YCLVL, C5_YSI, C5_YCLIORI, C5_YLOJORI, C5_YCODMUN,	" + Enter
			cSql += " CLI_ORIG = CASE WHEN C5_YCLIORI <> '' THEN C5_YCLIORI ELSE C5_CLIENTE END, "+ Enter
			cSql += " LOJ_ORIG = CASE WHEN C5_YLOJORI <> '' THEN C5_YLOJORI ELSE C5_LOJACLI END "+ Enter
			cSql += "FROM SC5010 WITH (NOLOCK) " + Enter
			cSql += "WHERE C5_FILIAL = '"+xFilial("SC5")+"' AND C5_NUM IN (SELECT C9_PEDIDO FROM "+nNomeSC9+" WHERE EMPRESA = '01') AND D_E_L_E_T_ = ''	" + Enter

		EndIf


		cSql += "UNION ALL	" + Enter
		cSql += "SELECT '13' AS 'EMPRESA' , C5_FILIAL,	C5_NUM,	C5_TIPO, C5_YEMP, C5_YLINHA,	C5_CLIENTE,	C5_LOJAENT,	C5_LOJACLI,	C5_YRECR,	C5_YSUBTP,	C5_TRANSP,	C5_TIPOCLI,	C5_CONDPAG,	C5_YFORMA,	C5_YMAXCND,	C5_YPERC,	" + Enter
		cSql += "	C5_YPRZINC,	C5_YDTINC,	C5_YPC,	C5_VLRFRET,	C5_YVLRREV,	C5_YCLIDEL,	C5_YPERDEL,	C5_YBAIDEL,	C5_YNFDEL,	C5_TABELA,	C5_VEND1,	C5_COMIS1,	C5_VEND2,	C5_COMIS2,	C5_VEND3,	C5_COMIS3,	C5_VEND4,	C5_COMIS4,	C5_VEND5,	" + Enter
		cSql += "	C5_COMIS5,	C5_DESC1,	C5_DESC2,	C5_DESC3,	C5_DESC4,	C5_BANCO,	C5_DESCFI,	C5_EMISSAO,	C5_COTACAO,	C5_PARC1,	C5_DATA1,	C5_PARC2,	C5_DATA2,	C5_PARC3,	C5_DATA3,	C5_PARC4,	C5_DATA4,	C5_TPFRETE,	C5_FRETE,	" + Enter
		cSql += "	C5_SEGURO,	C5_DESPESA,	C5_FRETAUT,	C5_REAJUST,	C5_MOEDA,	C5_PESOL,	C5_PBRUTO, C5_REIMP,	C5_REDESP,	C5_VOLUME1,	C5_VOLUME2,	C5_VOLUME3,	C5_VOLUME4,	C5_ESPECI1,	C5_ESPECI2,	C5_ESPECI3,	C5_ESPECI4,	C5_ACRSFIN,	C5_MENNOTA,	" + Enter
		cSql += "	C5_MENPAD,	C5_INCISS,	C5_LIBEROK,	C5_OK,	C5_NOTA,	C5_SERIE,	C5_VENDA,	C5_KITREP,	C5_TIPLIB,	C5_OS,	C5_YMARCA,	C5_YNUMERO,	C5_DESCONT,	C5_PEDEXP,	C5_TXMOEDA,	C5_USERLGI,	C5_USERLGA,	C5_YAAPROV,	C5_YAPROV,	C5_YDIGP,	" + Enter
		cSql += "	C5_YALTP,	C5_YOBS,	C5_TPCARGA,	C5_PREPEMB,	C5_CLIENT,	C5_PDESCAB,	C5_YFLAG,	C5_YEND,	C5_YEST,	C5_YMUN,	C5_YBAIRRO,	C5_YCEP,	C5_YTEL,	C5_YFATOR,	C5_YDESCLI,	C5_RECISS,	D_E_L_E_T_,	R_E_C_N_O_,	R_E_C_D_E_L_,	" + Enter
		cSql += "	C5_BLQ,	C5_FORNISS,	C5_CONTRA,	C5_VLR_FRT,	C5_YCC,	C5_YVLTOTP,	C5_YTPBLQ,	C5_YPEDPAI,	C5_YMEDDES,	C5_YMDESPD, C5_YPEDORI, C5_YITEMCT, C5_YCLVL, C5_YSI, C5_YCLIORI, C5_YLOJORI, C5_YCODMUN,	" + Enter
		cSql += " CLI_ORIG = CASE WHEN C5_YCLIORI <> '' THEN C5_YCLIORI ELSE C5_CLIENTE END, "+ Enter
		cSql += " LOJ_ORIG = CASE WHEN C5_YLOJORI <> '' THEN C5_YLOJORI ELSE C5_LOJACLI END "+ Enter
		cSql += "FROM SC5130 WITH (NOLOCK) " + Enter
		cSql += "WHERE C5_FILIAL = '"+xFilial("SC5")+"' AND C5_NUM IN (SELECT C9_PEDIDO FROM "+nNomeSC9+" WHERE EMPRESA = '13') AND D_E_L_E_T_ = ''	" + Enter

		//RUBENS JUNIOR (FACILE SISTEMAS) OS: 0516-14 DATA: 09/05/14
		cSql += "UNION ALL	" + Enter
		cSql += "SELECT '14' AS 'EMPRESA' , C5_FILIAL,	C5_NUM,	C5_TIPO, C5_YEMP, C5_YLINHA,	C5_CLIENTE,	C5_LOJAENT,	C5_LOJACLI,	C5_YRECR,	C5_YSUBTP,	C5_TRANSP,	C5_TIPOCLI,	C5_CONDPAG,	C5_YFORMA,	C5_YMAXCND,	C5_YPERC,	C5_YPRZINC,	C5_YDTINC,	" + Enter
		cSql += "		C5_YPC,	C5_VLRFRET,	C5_YVLRREV,	C5_YCLIDEL,	C5_YPERDEL,	C5_YBAIDEL,	C5_YNFDEL,	C5_TABELA,	C5_VEND1,	C5_COMIS1,	C5_VEND2,	C5_COMIS2,	C5_VEND3,	C5_COMIS3,	C5_VEND4,	C5_COMIS4,	C5_VEND5,	C5_COMIS5,	C5_DESC1,	C5_DESC2,	C5_DESC3,	" + Enter
		cSql += "		C5_DESC4,	C5_BANCO,	C5_DESCFI,	C5_EMISSAO,	C5_COTACAO,	C5_PARC1,	C5_DATA1,	C5_PARC2,	C5_DATA2,	C5_PARC3,	C5_DATA3,	C5_PARC4,	C5_DATA4,	C5_TPFRETE,	C5_FRETE,	C5_SEGURO,	C5_DESPESA,	C5_FRETAUT,	C5_REAJUST,	C5_MOEDA,	C5_PESOL,	" + Enter
		cSql += "		C5_PBRUTO,	C5_REIMP,	C5_REDESP,	C5_VOLUME1,	C5_VOLUME2,	C5_VOLUME3,	C5_VOLUME4,	C5_ESPECI1,	C5_ESPECI2,	C5_ESPECI3,	C5_ESPECI4,	C5_ACRSFIN,	C5_MENNOTA,	C5_MENPAD,	C5_INCISS,	C5_LIBEROK,	C5_OK,	C5_NOTA,	C5_SERIE,	C5_VENDA,	C5_KITREP,	" + Enter
		cSql += "		C5_TIPLIB,	C5_OS,	C5_YMARCA,	C5_YNUMERO,	C5_DESCONT,	C5_PEDEXP,	C5_TXMOEDA,	C5_USERLGI,	C5_USERLGA,	C5_YAAPROV,	C5_YAPROV,	C5_YDIGP,	C5_YALTP,	C5_YOBS,	C5_TPCARGA,	C5_PREPEMB,	C5_CLIENT,	C5_PDESCAB,	C5_YFLAG,	C5_YEND,	C5_YEST,	C5_YMUN,	" + Enter
		cSql += "		C5_YBAIRRO,	C5_YCEP,	C5_YTEL,	C5_YFATOR,	C5_YDESCLI,	C5_RECISS,	D_E_L_E_T_,	R_E_C_N_O_,	R_E_C_D_E_L_,	C5_BLQ,	C5_FORNISS,	C5_CONTRA,	C5_VLR_FRT,	C5_YCC,	C5_YVLTOTP,	C5_YTPBLQ,	C5_YPEDPAI,	C5_YMEDDES,	C5_YMDESPD, C5_YPEDORI, C5_YITEMCT, C5_YCLVL, " + Enter
		cSql += "		C5_YSI, C5_YCLIORI, C5_YLOJORI, C5_YCODMUN,	" + Enter
		cSql += " CLI_ORIG = CASE WHEN C5_YCLIORI <> '' THEN C5_YCLIORI ELSE C5_CLIENTE END, "+ Enter
		cSql += " LOJ_ORIG = CASE WHEN C5_YLOJORI <> '' THEN C5_YLOJORI ELSE C5_LOJACLI END "+ Enter
		cSql += "FROM SC5140 WITH (NOLOCK) " + Enter
		cSql += "WHERE C5_FILIAL = '"+xFilial("SC5")+"' AND C5_NUM IN (SELECT C9_PEDIDO FROM "+nNomeSC9+" WHERE EMPRESA = '14') AND D_E_L_E_T_ = ''	" + Enter

	EndIf		

	cSql += " ) AS TMP " + Enter
	cSql += " LEFT JOIN SC5_07 LC5 ON LC5.C5_YPEDORI = TMP.C5_NUM AND LC5.C5_CLIENTE = TMP.C5_YCLIORI AND LC5.C5_LOJACLI = TMP.C5_YLOJORI AND TMP.EMPRESA = LC5.C5_YEMPPED " + Enter
	TcSQLExec(cSql)


	//NOVA FUN«√O PARA CALCULAR O STATUS DO PEDIDO DE VENDA
	//U_BIAMsgRun("Aguarde... Atualizando status do Pedido...",,{|| U_fUpdSC62() })


	//GERA VIEW DA TABELA SC6
	cSql := ""
	//(Thiago Dantas - 26/03/15) -> alteraÁ„o para pegar a empresa Origem - Pedidos LM.
	cSql += ";WITH SC6_07 AS " + Enter
	cSql += "(SELECT C5_NUM, C5_YPEDORI, C5_YEMPPED, C6_PRODUTO, C6_ITEM, C6_YDTNECE, C6_ENTREG, F4_DUPLIC, F4_ESTOQUE	" + Enter
	cSql += "FROM SC5070 SC5 WITH (NOLOCK) INNER JOIN SC6070 SC6 WITH (NOLOCK) ON	" + Enter
	cSql += "		C5_NUM = C6_NUM  					" + Enter
	cSql += "     INNER JOIN SF4070 SF4 WITH (NOLOCK) ON " + Enter
	cSql += "		C6_TES 		= F4_CODIGO	AND			" + Enter
	cSQL += "		C6_FILIAL 	= F4_FILIAL  	 		" + Enter
	cSql += "WHERE C5_FILIAL = '01' 		AND			" + Enter
	cSql += "      C6_FILIAL = '01' 		AND 		" + Enter
	cSql += "      C6_QTDVEN-C6_QTDENT > 0	AND 		" + Enter
	cSql += "      C6_BLQ <> 'R' 			AND			" + Enter
	cSql += "      SC5.D_E_L_E_T_ = '' 		AND			" + Enter
	cSql += "      SC6.D_E_L_E_T_ = ''		AND 		" + Enter
	cSql += "      SF4.D_E_L_E_T_ = ''			)		" + Enter
	cSql += "											" + Enter
	cSql += "SELECT TMP.EMPRESA , TMP.C6_FILIAL,	TMP.C6_ITEM, TMP.C6_PRODUTO, TMP.C6_YEMP, TMP.C6_DESCRI, TMP.C6_UM,	TMP.C6_QTDVEN, TMP.C6_PRCVEN, TMP.C6_VALOR,	TMP.C6_QTDLIB, TMP.C6_TES, TMP.C6_CF, TMP.C6_SEGUM, " + Enter
	cSql += "	TMP.C6_UNSVEN, TMP.C6_LOCAL, TMP.C6_QTDEMP, TMP.C6_QTDENT, TMP.C6_CLI, TMP.C6_YPERC, TMP.C6_YDESC, TMP.C6_DESCONT, TMP.C6_VALDESC, (CASE WHEN ISNULL(LC6.C6_YDTNECE,TMP.C6_YDTNECE) <> '' THEN ISNULL(LC6.C6_YDTNECE,TMP.C6_YDTNECE) ELSE  ISNULL(LC6.C6_ENTREG,TMP.C6_ENTREG) END)  AS C6_ENTREG, " + Enter
	cSql += "	ISNULL(LC6.C6_YDTNECE,TMP.C6_YDTNECE) AS C6_YDTNECE, TMP.C6_LA,	TMP.C6_LOJA, TMP.C6_NOTA, TMP.C6_SERIE,	TMP.C6_DATFAT, TMP.C6_NUM, TMP.C6_COMIS1, TMP.C6_COMIS2, TMP.C6_COMIS3,	TMP.C6_COMIS4, TMP.C6_COMIS5, TMP.C6_YPALLET, " + Enter
	cSql += "	TMP.C6_PEDCLI, TMP.C6_PRUNIT,	TMP.C6_BLOQUEI,	TMP.C6_GEROUPV,	TMP.C6_RESERVA,	TMP.C6_OP, TMP.C6_OK, TMP.C6_NFORI,	TMP.C6_SERIORI,	TMP.C6_ITEMORI,	TMP.C6_IPIDEV, TMP.C6_IDENTB6, TMP.C6_BLQ, TMP.C6_PICMRET, TMP.C6_CODISS, " + Enter
	cSql += "	TMP.C6_GRADE,	TMP.C6_ITEMGRD,	TMP.C6_LOTECTL,	TMP.C6_NUMLOTE,	TMP.C6_DTVALID,	TMP.C6_NUMORC, TMP.C6_CHASSI, TMP.C6_OPC, TMP.C6_LOCALIZ, TMP.C6_NUMSERI, TMP.C6_NUMOP,	TMP.C6_ITEMOP, TMP.C6_CLASFIS, TMP.C6_YPESOL, " + Enter
	cSql += " 	TMP.C6_QTDRESE, TMP.C6_NUMOS, TMP.C6_NUMOSFA, TMP.C6_CODFAB, TMP.C6_LOJAFA, TMP.C6_TPOP, TMP.C6_REVISAO, TMP.C6_YEMISSA, TMP.C6_USERLGI, TMP.C6_USERLGA, TMP.C6_YIMPNF, TMP.C6_QTDLIB2, TMP.C6_QTDENT2, TMP.C6_SERVIC,	TMP.C6_ENDPAD, TMP.C6_CONTRT, " + Enter
	cSql += " 	TMP.C6_TPCONTR, TMP.C6_ITCONTR, TMP.C6_PROJPMS, TMP.C6_TASKPMS, TMP.C6_LICITA, TMP.C6_QTDEMP2, TMP.C6_CONTRAT, TMP.C6_ITEMCON, TMP.C6_TPESTR,	TMP.C6_EDTPMS, TMP.C6_TRT, TMP.C6_PROJET, TMP.C6_ITPROJ, TMP.C6_POTENCI, TMP.C6_REGWMS,	TMP.C6_MOPC, " + Enter
	cSql += " 	TMP.C6_NUMCP, TMP.C6_NUMSC, TMP.C6_ITEMSC, TMP.C6_SUGENTR,	TMP.C6_YPRCIMP,	TMP.C6_YCOD, TMP.C6_YQTDPC,	TMP.C6_YVLIMP,	TMP.C6_YPRCTAB,	TMP.C6_YDESCLI,	TMP.C6_YREGRA, TMP.C6_ICMSRET, TMP.C6_YDTRESI, " + Enter 
	cSql += "	ISNULL(LC6.F4_DUPLIC,TMP.F4_DUPLIC) AS F4_DUPLIC, ISNULL(LC6.F4_ESTOQUE,TMP.F4_ESTOQUE) AS F4_ESTOQUE, TMP.C6_YSTAT AS OBS " + Enter

	cSql += " INTO "+nNomeSC6+" FROM (" + Enter
	cSql += "SELECT '"+cEmpAnt+"' AS 'EMPRESA' , C6_FILIAL,	C6_ITEM,	C6_PRODUTO,	C6_YEMP, C6_DESCRI,	C6_UM,	C6_QTDVEN,	C6_PRCVEN,	C6_VALOR,	C6_QTDLIB,	C6_TES,	C6_CF,	C6_SEGUM,	C6_UNSVEN,	C6_LOCAL,	C6_QTDEMP,	C6_QTDENT,	C6_CLI,	C6_YPERC,	C6_YDESC,	" + Enter
	cSql += "	C6_DESCONT,	C6_VALDESC, (CASE WHEN C6_YDTNECE <> '' THEN C6_YDTNECE ELSE C6_ENTREG END) AS C6_ENTREG, C6_YDTNECE,	C6_LA,	C6_LOJA,	C6_NOTA,	C6_SERIE,	C6_DATFAT,	C6_NUM,	C6_COMIS1,	C6_COMIS2,	C6_COMIS3,	C6_COMIS4,	C6_COMIS5,	" + Enter
	cSql += "	C6_YPALLET,	C6_PEDCLI,	C6_PRUNIT,	C6_BLOQUEI,	C6_GEROUPV,	C6_RESERVA,	C6_OP,	C6_OK,	C6_NFORI,	C6_SERIORI,	C6_ITEMORI,	C6_IPIDEV,	C6_IDENTB6,	C6_BLQ,	C6_PICMRET,	C6_CODISS,	C6_GRADE,	C6_ITEMGRD,	C6_LOTECTL,	C6_NUMLOTE,	" + Enter
	cSql += "	C6_DTVALID,	C6_NUMORC,	C6_CHASSI,	C6_OPC,	C6_LOCALIZ,	C6_NUMSERI,	C6_NUMOP,	C6_ITEMOP,	C6_CLASFIS,	C6_YPESOL, F4_DUPLIC, F4_ESTOQUE,	C6_QTDRESE,	C6_NUMOS,	C6_NUMOSFA,	C6_CODFAB,	C6_LOJAFA,	C6_TPOP,	C6_REVISAO,	" + Enter
	cSql += "	C6_YEMISSA,	C6_USERLGI,	C6_USERLGA,	C6_YIMPNF,	C6_QTDLIB2,	C6_QTDENT2,	C6_SERVIC,	C6_ENDPAD,	C6_CONTRT,	C6_TPCONTR,	C6_ITCONTR,	C6_PROJPMS,	C6_TASKPMS,	C6_LICITA,	C6_QTDEMP2,	C6_CONTRAT,	C6_ITEMCON,	C6_TPESTR,	C6_EDTPMS,	" + Enter
	cSql += "	C6_TRT,	C6_PROJET,	C6_ITPROJ,	C6_POTENCI,	C6_REGWMS,	C6_MOPC,	C6_NUMCP,	C6_NUMSC,	C6_ITEMSC,	C6_SUGENTR,	C6_YPRCIMP,	C6_YCOD,	C6_YQTDPC,	C6_YVLIMP,	C6_YPRCTAB,	C6_YDESCLI,	C6_YREGRA,	C6_ICMSRET, C6_YDTRESI, C6_YSTAT " + Enter
	cSql += "FROM "+RetSqlName("SC6")+" A WITH (NOLOCK) " + Enter
	cSql += "INNER JOIN "+RetSqlName("SF4")+" F4 WITH (NOLOCK) ON C6_TES = F4_CODIGO AND C6_FILIAL = F4_FILIAL AND F4.D_E_L_E_T_   = '' " + Enter
	cSql += "WHERE C6_FILIAL = '"+xFilial("SC6")+"' AND C6_NUM IN (SELECT C9_PEDIDO FROM "+nNomeSC9+" WHERE EMPRESA = '"+cEmpAnt+"') AND A.D_E_L_E_T_ = '' " + Enter	
	cSql += " AND A.C6_BLQ <> 'R' " + Enter

	If cEmpAnt == "01"

		cSql += "UNION ALL " + Enter

		cSql += "SELECT '05' AS 'EMPRESA' , C6_FILIAL,	C6_ITEM,	C6_PRODUTO,	C6_YEMP, C6_DESCRI,	C6_UM,	C6_QTDVEN,	C6_PRCVEN,	C6_VALOR,	C6_QTDLIB,	C6_TES,	C6_CF,	C6_SEGUM,	C6_UNSVEN,	C6_LOCAL,	C6_QTDEMP,	" + Enter
		cSql += "		C6_QTDENT,	C6_CLI,	C6_YPERC,	C6_YDESC,	C6_DESCONT,	C6_VALDESC,(CASE WHEN C6_YDTNECE <> '' THEN C6_YDTNECE ELSE C6_ENTREG END) AS C6_ENTREG,C6_YDTNECE,	C6_LA,	C6_LOJA,	C6_NOTA,	C6_SERIE,	C6_DATFAT,	" + Enter
		cSql += "		C6_NUM,	C6_COMIS1,	C6_COMIS2,	C6_COMIS3,	C6_COMIS4,	C6_COMIS5,	C6_YPALLET,	C6_PEDCLI,	C6_PRUNIT,	C6_BLOQUEI,	C6_GEROUPV,	C6_RESERVA,	C6_OP,	C6_OK,	C6_NFORI,	C6_SERIORI,	C6_ITEMORI,	C6_IPIDEV,	C6_IDENTB6,	" + Enter
		cSql += "		C6_BLQ,	C6_PICMRET,	C6_CODISS,	C6_GRADE,	C6_ITEMGRD,	C6_LOTECTL,	C6_NUMLOTE,	C6_DTVALID,	C6_NUMORC,	C6_CHASSI,	C6_OPC,	C6_LOCALIZ,	C6_NUMSERI,	C6_NUMOP,	C6_ITEMOP,	C6_CLASFIS,	C6_YPESOL, F4_DUPLIC, F4_ESTOQUE,	" + Enter
		cSql += " 		C6_QTDRESE,	C6_NUMOS,	C6_NUMOSFA,	C6_CODFAB,	C6_LOJAFA,	C6_TPOP,	C6_REVISAO,	C6_YEMISSA,	C6_USERLGI,	C6_USERLGA,	C6_YIMPNF,	C6_QTDLIB2,	C6_QTDENT2,	C6_SERVIC,	C6_ENDPAD,	C6_CONTRT,	C6_TPCONTR,	" + Enter
		cSql += "		C6_ITCONTR,	C6_PROJPMS,	C6_TASKPMS,	C6_LICITA,	C6_QTDEMP2,	C6_CONTRAT,	C6_ITEMCON,	C6_TPESTR,	C6_EDTPMS,	C6_TRT,	C6_PROJET,	C6_ITPROJ,	C6_POTENCI,	C6_REGWMS,	C6_MOPC,	C6_NUMCP,	C6_NUMSC,	C6_ITEMSC,	" + Enter
		cSql += "		C6_SUGENTR,	C6_YPRCIMP,	C6_YCOD,	C6_YQTDPC,	C6_YVLIMP,	C6_YPRCTAB,	C6_YDESCLI,	C6_YREGRA,	C6_ICMSRET, C6_YDTRESI, C6_YSTAT " + Enter
		cSql += "FROM SC6050 A WITH (NOLOCK) " + Enter
		cSql += "INNER JOIN SF4050 F4 WITH (NOLOCK) ON C6_TES = F4_CODIGO AND C6_FILIAL 	= F4_FILIAL AND F4.D_E_L_E_T_   = '' " + Enter	

		// Tiago Rossini Coradini - 01/08/16 - OS: 2813-16 - Claudeir Fadini - Ajuste no filtro de produtos por marca	
		cSql += " WHERE A.C6_FILIAL	= '01' " + Enter
		cSql += "	AND A.C6_YEMISSA >= '20120101' " + Enter
		cSql += "	AND A.C6_BLQ <> 'R' " + Enter 
		cSql += "	AND A.C6_NUM IN ( " + Enter
		cSql += "		SELECT C9_PEDIDO FROM "+nNomeSC9 + Enter 
		cSql += "		WHERE EMPRESA = '05' " + Enter
		cSql += "		AND MARCA = '0101' ) " + Enter
		cSql += "	AND A.D_E_L_E_T_	= '' " + Enter

	EndIf

	// Tiago Rossini Coradini - 02/08/16 - OS: 2813-16 - Claudeir Fadini - Ajuste no filtro de produtos por marca
	If cEmpAnt == "05"

		cSql += "UNION ALL " + Enter

		cSql += "SELECT '01' AS 'EMPRESA' , C6_FILIAL,	C6_ITEM,	C6_PRODUTO,	C6_YEMP, C6_DESCRI,	C6_UM,	C6_QTDVEN,	C6_PRCVEN,	C6_VALOR,	C6_QTDLIB,	C6_TES,	C6_CF,	C6_SEGUM,	C6_UNSVEN,	C6_LOCAL,	C6_QTDEMP,	" + Enter
		cSql += "		C6_QTDENT,	C6_CLI,	C6_YPERC,	C6_YDESC,	C6_DESCONT,	C6_VALDESC,(CASE WHEN C6_YDTNECE <> '' THEN C6_YDTNECE ELSE C6_ENTREG END) AS C6_ENTREG,C6_YDTNECE,	C6_LA,	C6_LOJA,	C6_NOTA,	C6_SERIE,	C6_DATFAT,	" + Enter
		cSql += "		C6_NUM,	C6_COMIS1,	C6_COMIS2,	C6_COMIS3,	C6_COMIS4,	C6_COMIS5,	C6_YPALLET,	C6_PEDCLI,	C6_PRUNIT,	C6_BLOQUEI,	C6_GEROUPV,	C6_RESERVA,	C6_OP,	C6_OK,	C6_NFORI,	C6_SERIORI,	C6_ITEMORI,	C6_IPIDEV,	C6_IDENTB6,	" + Enter
		cSql += "		C6_BLQ,	C6_PICMRET,	C6_CODISS,	C6_GRADE,	C6_ITEMGRD,	C6_LOTECTL,	C6_NUMLOTE,	C6_DTVALID,	C6_NUMORC,	C6_CHASSI,	C6_OPC,	C6_LOCALIZ,	C6_NUMSERI,	C6_NUMOP,	C6_ITEMOP,	C6_CLASFIS,	C6_YPESOL, F4_DUPLIC, F4_ESTOQUE,	" + Enter
		cSql += " 		C6_QTDRESE,	C6_NUMOS,	C6_NUMOSFA,	C6_CODFAB,	C6_LOJAFA,	C6_TPOP,	C6_REVISAO,	C6_YEMISSA,	C6_USERLGI,	C6_USERLGA,	C6_YIMPNF,	C6_QTDLIB2,	C6_QTDENT2,	C6_SERVIC,	C6_ENDPAD,	C6_CONTRT,	C6_TPCONTR,	" + Enter
		cSql += "		C6_ITCONTR,	C6_PROJPMS,	C6_TASKPMS,	C6_LICITA,	C6_QTDEMP2,	C6_CONTRAT,	C6_ITEMCON,	C6_TPESTR,	C6_EDTPMS,	C6_TRT,	C6_PROJET,	C6_ITPROJ,	C6_POTENCI,	C6_REGWMS,	C6_MOPC,	C6_NUMCP,	C6_NUMSC,	C6_ITEMSC,	" + Enter
		cSql += "		C6_SUGENTR,	C6_YPRCIMP,	C6_YCOD,	C6_YQTDPC,	C6_YVLIMP,	C6_YPRCTAB,	C6_YDESCLI,	C6_YREGRA,	C6_ICMSRET, C6_YDTRESI, C6_YSTAT " + Enter
		cSql += "FROM SC6010 A WITH (NOLOCK) " + Enter
		cSql += "INNER JOIN SF4010 F4 WITH (NOLOCK) ON C6_TES = F4_CODIGO AND C6_FILIAL 	= F4_FILIAL AND F4.D_E_L_E_T_   = '' " + Enter	

		// Tiago Rossini Coradini - 02/08/16 - OS: 2813-16 - Claudeir Fadini - Ajuste no filtro de produtos por marca	
		cSql += " WHERE A.C6_FILIAL	= '01' " + Enter	
		cSql += "	AND A.C6_YEMISSA >= '20120101' " + Enter
		cSql += "	AND A.C6_BLQ <> 'R' " + Enter 
		cSql += "	AND A.C6_NUM IN ( " + Enter
		cSql += "		SELECT C9_PEDIDO FROM "+nNomeSC9 + Enter 
		cSql += "		WHERE EMPRESA = '01' " + Enter
		cSql += "		AND MARCA IN ('0501', '0599') ) " + Enter
		cSql += "	AND A.D_E_L_E_T_	= '' " + Enter

	EndIf

	If cEmpAnt $ "01_05"	

		cSql += "UNION ALL	" + Enter

		cSql += "SELECT '13' AS 'EMPRESA' , C6_FILIAL,	C6_ITEM,	C6_PRODUTO,	C6_YEMP, C6_DESCRI,	C6_UM,	C6_QTDVEN,	C6_PRCVEN,	C6_VALOR,	C6_QTDLIB,	C6_TES,	C6_CF,	C6_SEGUM,	C6_UNSVEN,	C6_LOCAL,	C6_QTDEMP,	" + Enter
		cSql += "		C6_QTDENT,	C6_CLI,	C6_YPERC,	C6_YDESC,	C6_DESCONT,	C6_VALDESC,(CASE WHEN C6_YDTNECE <> '' THEN C6_YDTNECE ELSE C6_ENTREG END) AS C6_ENTREG,C6_YDTNECE,	C6_LA,	C6_LOJA,	C6_NOTA,	C6_SERIE,	C6_DATFAT,	" + Enter
		cSql += "		C6_NUM,	C6_COMIS1,	C6_COMIS2,	C6_COMIS3,	C6_COMIS4,	C6_COMIS5,	C6_YPALLET,	C6_PEDCLI,	C6_PRUNIT,	C6_BLOQUEI,	C6_GEROUPV,	C6_RESERVA,	C6_OP,	C6_OK,	C6_NFORI,	C6_SERIORI,	C6_ITEMORI,	C6_IPIDEV,	C6_IDENTB6,	" + Enter
		cSql += "		C6_BLQ,	C6_PICMRET,	C6_CODISS,	C6_GRADE,	C6_ITEMGRD,	C6_LOTECTL,	C6_NUMLOTE,	C6_DTVALID,	C6_NUMORC,	C6_CHASSI,	C6_OPC,	C6_LOCALIZ,	C6_NUMSERI,	C6_NUMOP,	C6_ITEMOP,	C6_CLASFIS,	C6_YPESOL, F4_DUPLIC,F4_ESTOQUE,	" + Enter
		cSql += "		C6_QTDRESE,	C6_NUMOS,	C6_NUMOSFA,	C6_CODFAB,	C6_LOJAFA,	C6_TPOP,	C6_REVISAO,	C6_YEMISSA,	C6_USERLGI,	C6_USERLGA,	C6_YIMPNF,	C6_QTDLIB2,	C6_QTDENT2,	C6_SERVIC,	C6_ENDPAD,	C6_CONTRT,	C6_TPCONTR,	" + Enter
		cSql += "		C6_ITCONTR,	C6_PROJPMS,	C6_TASKPMS,	C6_LICITA,	C6_QTDEMP2,	C6_CONTRAT,	C6_ITEMCON,	C6_TPESTR,	C6_EDTPMS,	C6_TRT,	C6_PROJET,	C6_ITPROJ,	C6_POTENCI,	C6_REGWMS,	C6_MOPC,	C6_NUMCP,	C6_NUMSC,	C6_ITEMSC,	C6_SUGENTR,	" + Enter
		cSql += "		C6_YPRCIMP,	C6_YCOD,	C6_YQTDPC,	C6_YVLIMP,	C6_YPRCTAB,	C6_YDESCLI,	C6_YREGRA,	C6_ICMSRET, C6_YDTRESI, C6_YSTAT " + Enter
		cSql += "FROM SC6130 A WITH (NOLOCK) " + Enter
		cSql += "INNER JOIN SF4130 F4 WITH (NOLOCK) ON C6_TES = F4_CODIGO AND C6_FILIAL 	= F4_FILIAL AND F4.D_E_L_E_T_   = '' " + Enter

		// Tiago Rossini Coradini - 01/08/16 - OS: 2813-16 - Claudeir Fadini - Ajuste no filtro de produtos por marca	
		cSql += " WHERE A.C6_FILIAL	= '01' " + Enter	
		cSql += "	AND A.C6_YEMISSA >= '20120101' " + Enter
		cSql += "	AND A.C6_BLQ <> 'R' " + Enter 
		cSql += "	AND A.C6_NUM IN (" + Enter
		cSql += "		SELECT C9_PEDIDO FROM "+nNomeSC9 + Enter 
		cSql += "		WHERE EMPRESA = '13' " + Enter
		cSql += "		AND MARCA " + If (cEmpAnt == "01", "=", "<>") + ValToSQL("0101") + " ) " + Enter
		cSql += "	AND A.D_E_L_E_T_	= '' " + Enter

		cSql += "UNION ALL	" + Enter

		cSql += "SELECT '14' AS 'EMPRESA' , C6_FILIAL,	C6_ITEM,	C6_PRODUTO,	C6_YEMP, C6_DESCRI,	C6_UM,	C6_QTDVEN,	C6_PRCVEN,	C6_VALOR,	C6_QTDLIB,	C6_TES,	C6_CF,	C6_SEGUM,	C6_UNSVEN,	C6_LOCAL,	C6_QTDEMP,	" + Enter
		cSql += "		C6_QTDENT,	C6_CLI,	C6_YPERC,	C6_YDESC,	C6_DESCONT,	C6_VALDESC,(CASE WHEN C6_YDTNECE <> '' THEN C6_YDTNECE ELSE C6_ENTREG END) AS C6_ENTREG,C6_YDTNECE,	C6_LA,	C6_LOJA,	C6_NOTA,	C6_SERIE,	C6_DATFAT,	" + Enter
		cSql += "		C6_NUM,	C6_COMIS1,	C6_COMIS2,	C6_COMIS3,	C6_COMIS4,	C6_COMIS5,	C6_YPALLET,	C6_PEDCLI,	C6_PRUNIT,	C6_BLOQUEI,	C6_GEROUPV,	C6_RESERVA,	C6_OP,	C6_OK,	C6_NFORI,	C6_SERIORI,	C6_ITEMORI,	C6_IPIDEV,	C6_IDENTB6,	" + Enter
		cSql += "		C6_BLQ,	C6_PICMRET,	C6_CODISS,	C6_GRADE,	C6_ITEMGRD,	C6_LOTECTL,	C6_NUMLOTE,	C6_DTVALID,	C6_NUMORC,	C6_CHASSI,	C6_OPC,	C6_LOCALIZ,	C6_NUMSERI,	C6_NUMOP,	C6_ITEMOP,	C6_CLASFIS,	C6_YPESOL, F4_DUPLIC, F4_ESTOQUE,	" + Enter
		cSql += "		C6_QTDRESE,	C6_NUMOS,	C6_NUMOSFA,	C6_CODFAB,	C6_LOJAFA,	C6_TPOP,	C6_REVISAO,	C6_YEMISSA,	C6_USERLGI,	C6_USERLGA,	C6_YIMPNF,	C6_QTDLIB2,	C6_QTDENT2,	C6_SERVIC,	C6_ENDPAD,	C6_CONTRT,	C6_TPCONTR,	C6_ITCONTR,	" + Enter
		cSql += "		C6_PROJPMS,	C6_TASKPMS,	C6_LICITA,	C6_QTDEMP2,	C6_CONTRAT,	C6_ITEMCON,	C6_TPESTR,	C6_EDTPMS,	C6_TRT,	C6_PROJET,	C6_ITPROJ,	C6_POTENCI,	C6_REGWMS,	C6_MOPC,	C6_NUMCP,	C6_NUMSC,	C6_ITEMSC,	C6_SUGENTR,	C6_YPRCIMP,	C6_YCOD, " + Enter
		cSql += "		C6_YQTDPC,	C6_YVLIMP,	C6_YPRCTAB,	C6_YDESCLI,	C6_YREGRA,	C6_ICMSRET, C6_YDTRESI, C6_YSTAT " + Enter
		cSql += "FROM SC6140 A WITH (NOLOCK) " + Enter
		cSql += "INNER JOIN SF4140 F4 WITH (NOLOCK) ON C6_TES = F4_CODIGO AND C6_FILIAL 	= F4_FILIAL AND F4.D_E_L_E_T_   = '' " + Enter

		// Tiago Rossini Coradini - 01/08/16 - OS: 2813-16 - Claudeir Fadini - Ajuste no filtro de produtos por marca
		cSql += " WHERE A.C6_FILIAL	= '01' " + Enter	
		cSql += "	AND A.C6_YEMISSA >= '20120101' " + Enter
		cSql += "	AND A.C6_BLQ <> 'R' " + Enter 
		cSql += "	AND A.C6_NUM IN (" + Enter
		cSql += "		SELECT C9_PEDIDO FROM "+nNomeSC9 + Enter 
		cSql += "		WHERE EMPRESA = '14' " + Enter
		cSql += "		AND MARCA " + If (cEmpAnt == "01", "=", "<>") + ValToSQL("0101") + " ) " + Enter
		cSql += "	AND A.D_E_L_E_T_	= '' " + Enter

	EndIf
	cSql += " ) AS TMP " + Enter 
	cSql += " LEFT JOIN SC6_07 LC6	ON TMP.C6_NUM = LC6.C5_YPEDORI AND LC6.C5_YEMPPED = TMP.EMPRESA AND LC6.C6_ITEM = TMP.C6_ITEM AND LC6.C6_PRODUTO = TMP.C6_PRODUTO " + Enter
	TcSQLExec(cSql)

	//Chama funcao que atualiza o status de cada Item do Pedido (tabela temporaria)
	//U_BIAMsgRun("Aguarde... Gerando Base... Atualizando status do Pedido...",,{|| U_fUpdSC6(nNomeSC6) })

	//SELECIONA AS TRANSPORTADORAS DOS ROMANEIOS EM ABERTO
	CSQL := ""
	CSQL += "SELECT  * FROM (
	CSQL += "SELECT C5_TRANSP, A4_COD, A4_NOME, A4_TEL, A4_EMAIL											" + Enter
	CSQL += "FROM "+nNomeSC9+" SC9, "+nNomeSC6+" SC6, SA4010 SA4 WITH (NOLOCK),	" + ENTER
	CSQL += "		(SELECT	C5.C5_FILIAL, C5.EMPRESA, C5.C5_NUM, C5.C5_TIPO, C5.C5_CLIENTE, C5.C5_LOJACLI, C5.C5_EMISSAO, C5.C5_YLINHA, C5.C5_YCLIORI, C5.C5_YLOJORI, C5.C5_YAPROV, C5.C5_VEND1, C5.C5_TRANSP " + ENTER
	CSQL += "		 FROM "+nNomeSC5+" AS C5 WITH (NOLOCK) ) SC5 " + Enter
	CSQL += "WHERE	SC9.C9_FILIAL	= '"+xFilial("SC9")+"'	AND	" + ENTER
	CSQL += "		SA4.A4_FILIAL	= '"+xFilial("SA4")+"'	AND	" + ENTER
	CSQL += "		SC6.C6_FILIAL	= '"+xFilial("SC6")+"'	AND	" + ENTER
	CSQL += "		SC5.EMPRESA		= SC6.EMPRESA			AND	" + Enter		//LINK VIRTUAL EMPRESA
	CSQL += "		SC5.C5_TRANSP	= SA4.A4_COD			AND	" + ENTER
	CSQL += "		SC5.C5_NUM		= SC6.C6_NUM			AND	" + ENTER
	CSQL += "		SC5.C5_CLIENTE	= SC6.C6_CLI			AND	" + ENTER
	CSQL += "		SC5.C5_LOJACLI	= SC6.C6_LOJA			AND	" + ENTER
	CSQL += "		SC6.EMPRESA		= SC9.EMPRESA			AND	" + ENTER  //LINK VIRTUAL EMPRESA
	CSQL += "		SC6.C6_NUM		= SC9.C9_PEDIDO 		AND " + ENTER
	CSQL += "		SC6.C6_PRODUTO	= SC9.C9_PRODUTO		AND " + ENTER
	CSQL += "		SC6.C6_ITEM		= SC9.C9_ITEM			AND " + ENTER
	cSql += "		SC9.C9_NFISCAL	= '' AND " + Enter
	cSql += "		SC9.C9_BLEST	= '' AND " + Enter //NOVO
	cSql += "		SC9.C9_BLCRED	= '' AND " + Enter //NOVO
	CSQL += "		SA4.D_E_L_E_T_  = ''									" + ENTER
	CSQL += " 	GROUP BY C5_TRANSP, A4_COD, A4_NOME, A4_TEL, A4_EMAIL ) TMP	" + ENTER
	CSQL += "ORDER BY C5_TRANSP 											" + ENTER
	IF CHKFILE("S_TRAB")
		DBSELECTAREA("S_TRAB")
		DBCLOSEAREA()
	ENDIF
	TCQUERY CSQL ALIAS "S_TRAB" NEW
	DBSELECTAREA("S_TRAB")
	DBGOTOP()

	DO WHILE ! S_TRAB->(EOF())

		CEMAIL 	:= ALLTRIM(S_TRAB->A4_EMAIL)
		CCODIGO := ALLTRIM(S_TRAB->A4_COD)
		CNOME 	:= ALLTRIM(S_TRAB->A4_NOME)

		cSql := ""
		cSql += "SELECT EMPRESA, A4_COD, A4_NOME, A4_TEL, A3_COD, A3_NOME, A3_NREDUZ, A3_TEL, A1_COD, A1_NOME, A1_CGC, A1_TEL, A1_BAIRRO, A1_MUN, A1_EST, A1_CEP, C5_NUM, C6_PRODUTO, C6_ENTREG,C6_YDTNECE, C5_YPC, SUM(PESOBR_IMEDIATO) AS PESOBR_IMEDIATO, SUM(PESOBR_7DIAS) PESOBR_7DIAS, SUM(Z9_PESOBR) AS Z9_PESOBR, AVG(DIAS) AS DIAS " + Enter
		cSql += "FROM " + Enter
		cSql += "(SELECT SC5.EMPRESA, SC5.C5_NUM, SC5.C5_YPC, A4_COD, A4_NOME, A4_TEL, A3_COD, A3_NOME, A3_NREDUZ, A3_TEL, A1_COD, C5_YCLIORI, C5_YLOJORI,	" + Enter	
		cSql += "				SC6.OBS AS SIT,	" + Enter
		cSql += "				A1_NOME = CASE	" + Enter
		cSql += "									WHEN C5_TIPO = 'N' THEN A1_NOME ELSE (SELECT A2_NOME FROM SA2010 WITH (NOLOCK) WHERE A2_COD = C5_YCLIORI AND A2_LOJA = C5_YLOJORI AND D_E_L_E_T_ = '') 	" + Enter
		cSql += "			 					END,		" + Enter
		cSql += "				A1_CGC = CASE 	" + Enter
		cSql += "									WHEN C5_TIPO = 'N' THEN A1_CGC ELSE (SELECT A2_CGC FROM SA2010 WITH (NOLOCK) WHERE A2_COD = C5_YCLIORI AND A2_LOJA = C5_YLOJORI AND D_E_L_E_T_ = '') 	" + Enter
		cSql += "				 				END, 		" + Enter
		cSql += "				A1_TEL = CASE 	" + Enter
		cSql += "									WHEN C5_TIPO = 'N' THEN A1_TEL ELSE (SELECT A2_TEL FROM SA2010 WITH (NOLOCK) WHERE A2_COD = C5_YCLIORI AND A2_LOJA = C5_YLOJORI AND D_E_L_E_T_ = '') 	" + Enter
		cSql += "								END, 		" + Enter
		cSql += "				GRUPO = CASE 		" + Enter
		cSql += "									WHEN A1_GRPVEN = '' THEN A1_COD ELSE A1_GRPVEN			" + Enter
		cSql += "				 				END,		" + Enter
		cSql += "				NOMEGRU = CASE  " + Enter
		cSql += "				   				WHEN A1_GRPVEN = '' AND C5_TIPO = 'N' THEN A1_NOME	" + Enter
		cSql += "				   				WHEN A1_GRPVEN = '' AND C5_TIPO = 'B' THEN (SELECT A2_NOME FROM SA2010 WITH (NOLOCK) WHERE A2_COD = C5_YCLIORI AND A2_LOJA = C5_YLOJORI AND D_E_L_E_T_ = '')		" + Enter
		cSql += "				   				ELSE ACY_DESCRI		" + Enter
		cSql += "	      				END, 			" + Enter
		cSql += "				A1_BAIRRO = CASE	" + Enter
		cSql += "									WHEN C5_YFLAG = '1' AND C5_TIPO = 'N' THEN A1_BAIRRO	" + Enter
		cSql += "									WHEN C5_YFLAG = '1' AND C5_TIPO = 'B' THEN (SELECT A2_BAIRRO FROM SA2010 WITH (NOLOCK) WHERE A2_COD = C5_YCLIORI AND A2_LOJA = C5_YLOJORI AND D_E_L_E_T_ = '')	" + Enter
		cSql += "									ELSE C5_YBAIRRO 	" + Enter
		cSql += "				 				END, 			" + Enter
		cSql += "				A1_MUN = CASE			" + Enter
		cSql += "									WHEN C5_YFLAG = '1' AND C5_TIPO = 'N' THEN A1_MUN	" + Enter
		cSql += "									WHEN C5_YFLAG = '1' AND C5_TIPO = 'B' THEN (SELECT A2_MUN FROM SA2010 WITH (NOLOCK) WHERE A2_COD = C5_YCLIORI AND A2_LOJA = C5_YLOJORI AND D_E_L_E_T_ = '')	" + Enter
		cSql += "									ELSE C5_YMUN			" + Enter
		cSql += "				 				END,			" + Enter
		cSql += "				A1_EST = CASE 		" + Enter
		cSql += "									WHEN C5_YFLAG = '1' AND C5_TIPO = 'N' THEN A1_EST 	" + Enter
		cSql += "									WHEN C5_YFLAG = '1' AND C5_TIPO = 'B' THEN (SELECT A2_EST FROM SA2010 WITH (NOLOCK) WHERE A2_COD = C5_YCLIORI AND A2_LOJA = C5_YLOJORI AND D_E_L_E_T_ = '') 	" + Enter
		cSql += "									ELSE C5_YEST 	" + Enter
		cSql += "				 				END,			" + Enter
		cSql += "				A1_CEP = CASE 		" + Enter
		cSql += "									WHEN C5_YFLAG = '1' AND C5_TIPO = 'N' THEN A1_CEP 	" + Enter 	
		cSql += "									WHEN C5_YFLAG = '1' AND C5_TIPO = 'B' THEN (SELECT A2_CEP FROM SA2010 WITH (NOLOCK) WHERE A2_COD = C5_YCLIORI AND A2_LOJA = C5_YLOJORI AND D_E_L_E_T_ = '') 	" + Enter
		cSql += "									ELSE C5_YCEP 	" + Enter
		cSql += "				 				END,			" + Enter
		cSql += "				C6_PRODUTO, C6_ENTREG, C6_YDTNECE, C9_DATALIB AS Z9_EMISSAO, C5_EMISSAO, " + Enter 	 
		cSql += "				((C9_QTDLIB*ISNULL(ZZ9_PESO,B1_PESO))+(C9_QTDLIB2*ISNULL(ZZ9_PESEMB,B1_YPESEMB))) AS Z9_PESOBR,	" + Enter
		cSql += "				PESOBR_IMEDIATO = CASE																			" + Enter
		cSql += "							WHEN C6_ENTREG <= CONVERT(VARCHAR,GETDATE(),112) THEN ((C9_QTDLIB*ISNULL(ZZ9_PESO,B1_PESO))+(C9_QTDLIB2*ISNULL(ZZ9_PESEMB,B1_YPESEMB))) " + Enter
		cSql += "							ELSE 0					" + Enter
		cSql += "						  END,						" + Enter
		cSql += "  				PESOBR_7DIAS = CASE					" + Enter
		cSql += "							WHEN C6_ENTREG > CONVERT(VARCHAR,GETDATE(),112)	THEN ((C9_QTDLIB*ISNULL(ZZ9_PESO,B1_PESO))+(C9_QTDLIB2*ISNULL(ZZ9_PESEMB,B1_YPESEMB))) " + Enter
		cSql += "							ELSE 0					" + Enter
		cSql += "						  END,						" + Enter		
		cSql += "				C5_VEND1, C5_VEND2, C9_PEDIDO AS Z9_PEDIDO, C9_AGREG AS Z9_AGREG, '' AS Z9_NUMERO, C9_PRODUTO AS Z9_PRODUTO, C6_DESCRI AS Z9_DESCRIC, C6_UM AS B1_UM, C9_QTDLIB, C9_QTDLIB2,	" + Enter
		cSql += "				DIAS = CASE WHEN C6_YDTNECE <> '' THEN DATEDIFF(D,C6_YDTNECE, GETDATE()) 	ELSE DATEDIFF(D,C9_DATALIB, GETDATE()) END " + Enter
		cSql += "FROM	" + Enter

		//(Thiago - 27/03/15) -> para melhorar a performance.
		cSql += "			(SELECT C5.C5_FILIAL, C5.EMPRESA, C5.C5_NUM, C5.C5_YPC, C5.C5_TIPO, C5.C5_CLIENTE, C5.C5_LOJACLI, C5.C5_EMISSAO, C5.C5_YLINHA,	" + Enter
		cSql += "						C5.C5_YAPROV,	"+ Enter
		cSql += "						C5.C5_VEND1,	"+ Enter
		cSql += "						C5.C5_VEND2,	"+ Enter
		//
		cSql += "						C5.C5_YCEP,	"+ Enter
		//
		cSql += "						C5.C5_YCLIORI AS 'LM', " + Enter
		cSql += "						C5.C5_TRANSP,	" + Enter
		cSql += "						C5_YCLIORI = CASE WHEN C5.C5_YCLIORI = '' THEN C5.C5_CLIENTE ELSE C5.C5_YCLIORI END,	" + Enter
		cSql += "						C5_YLOJORI = CASE WHEN C5.C5_YLOJORI = '' THEN C5.C5_LOJACLI ELSE C5.C5_YLOJORI END,	" + Enter
		cSql += "						C5.C5_YFLAG, C5.C5_YBAIRRO, C5.C5_YMUN, C5.C5_YEST,C5.C5_YCODMUN, C5.C5_CONDPAG			" + Enter
		cSql += "						FROM "+nNomeSC5+" AS C5	) SC5 															" + Enter

		cSql += "		INNER JOIN 
		cSql += "		(SELECT * 	" + Enter  
		cSql += "		FROM "+nNomeSC6+" AS ZZZ WHERE C6_FILIAL = '"+xFilial('SC6')+"') SC6	" + Enter
		cSql += "		ON  SC5.EMPRESA		= SC6.EMPRESA	" + Enter
		cSql += "		AND SC5.C5_NUM		= SC6.C6_NUM	" + Enter
		cSql += "		AND SC5.C5_CLIENTE	= SC6.C6_CLI	" + Enter
		cSql += "		AND SC5.C5_LOJACLI	= SC6.C6_LOJA	" + Enter

		cSql += "		INNER JOIN "+nNomeSC9+" SC9				" + Enter
		cSql += "		ON  SC5.EMPRESA		= SC6.EMPRESA		" + Enter
		cSql += "		AND SC5.C5_NUM		= SC6.C6_NUM		" + Enter
		cSql += "		AND SC5.C5_CLIENTE	= SC6.C6_CLI		" + Enter
		cSql += "		AND SC5.C5_LOJACLI	= SC6.C6_LOJA		" + Enter
		cSql += "		AND SC5.C5_NUM		= SC9.C9_PEDIDO		" + Enter
		cSql += "		AND SC5.C5_CLIENTE	= SC9.C9_CLIENTE	" + Enter
		cSql += "		AND SC5.C5_LOJACLI	= SC9.C9_LOJA		" + Enter
		cSql += "		AND SC6.EMPRESA		= SC9.EMPRESA  		" + Enter	
		cSql += "		AND SC6.C6_NUM		= SC9.C9_PEDIDO 	" + Enter
		cSql += "		AND SC6.C6_PRODUTO	= SC9.C9_PRODUTO	" + Enter
		cSql += "		AND SC6.C6_ITEM		= SC9.C9_ITEM		" + Enter

		cSql += "		INNER JOIN 
		cSql += "		(SELECT *	" + Enter
		cSql += " 		 FROM					" + Enter
		cSql += " 			(SELECT *,			" + Enter
		cSql += "				RISCO = CASE															" + Enter
		cSql += "							WHEN A1_RISCO = 'B' THEN "+STR(GETMV('MV_RISCOB'))+" " + Enter
		cSql += "							WHEN A1_RISCO = 'C' THEN "+STR(GETMV('MV_RISCOC'))+" " + Enter
		cSql += "							WHEN A1_RISCO = 'D' THEN "+STR(GETMV('MV_RISCOD'))+" " + Enter
		cSql += "							WHEN A1_RISCO = 'E' THEN 0			" + Enter
		cSql += "							ELSE 999999							" + Enter
		cSql += "						END									    " + Enter
		cSql += "		FROM "+RetSqlName("SA1")+" WITH (NOLOCK)				" + Enter
		cSql += "		WHERE A1_FILIAL = '"+xFilial('SA1')+"' AND D_E_L_E_T_ = '' )TMP  )SA1 	" + Enter
		cSql += "		ON SA1.A1_FILIAL	= '"+xFilial("SA1")+"' 	" + Enter
		cSql += "		AND SC5.C5_YCLIORI	= SA1.A1_COD		 	" + Enter
		cSql += "		AND SC5.C5_YLOJORI	= SA1.A1_LOJA			" + Enter
		cSql += "		AND SA1.D_E_L_E_T_	= '' 					" + Enter

		cSql += " 		INNER JOIN "+RetSqlName("SE4") +" E4  WITH (NOLOCK) ON E4.E4_FILIAL 	= '"+xFilial('SE4')+"' AND SC5.C5_CONDPAG  	= E4.E4_CODIGO  AND E4.D_E_L_E_T_   = ''" + Enter
		cSql += " 		INNER JOIN "+RetSqlName("SA3") +" SA3 WITH (NOLOCK) ON SA3.A3_FILIAL	= '"+xFilial("SA3")+"' AND SC5.C5_VEND1		= SA3.A3_COD 	AND SA3.D_E_L_E_T_	= ''" + Enter
		cSql += " 		INNER JOIN "+RetSqlName("SB1") +" SB1 WITH (NOLOCK) ON SB1.B1_FILIAL	= '"+xFilial("SB1")+"' AND SC9.C9_PRODUTO 	= SB1.B1_COD 	AND SB1.D_E_L_E_T_	= ''" + Enter

		cSql += " 		LEFT JOIN "+RetSqlName("SA4")  +" SA4 WITH (NOLOCK) ON SA4.A4_FILIAL	= '"+xFilial("SA4")+"' AND SC5.C5_TRANSP	= SA4.A4_COD 	AND SA4.D_E_L_E_T_	= ''" + Enter
		cSql += "		LEFT JOIN ACY010 ACY WITH (NOLOCK) ON ACY.ACY_FILIAL	= '"+xFilial("ACY")+"'	AND SA1.A1_GRPVEN	= ACY.ACY_GRPVEN AND ACY.D_E_L_E_T_ = ''" + Enter
		cSql += "		LEFT JOIN ZZ9010 ZZ9 WITH (NOLOCK) ON ZZ9.ZZ9_FILIAL	= '"+xFilial("ZZ9")+"'	AND SC9.C9_PRODUTO	= ZZ9.ZZ9_PRODUT AND SC9.C9_LOTECTL	= ZZ9.ZZ9_LOTE	AND ZZ9.D_E_L_E_T_ = '' " + Enter
		cSql += "WHERE	SC6.C6_FILIAL	= '"+xFilial("SC6")+"' AND " + Enter
		cSql += "		SC9.C9_FILIAL	= '"+xFilial("SC9")+"' AND " + Enter
		cSql += "		SA1.A1_FILIAL	= '"+xFilial("SA1")+"' 	AND " + Enter
		cSql += "		SA3.A3_FILIAL	= '"+xFilial("SA3")+"' 	AND " + Enter
		cSql += "		SA4.A4_FILIAL	= '"+xFilial("SA4")+"' 	AND	" + Enter
		cSql += "		SC5.EMPRESA		= SC6.EMPRESA	AND	" + Enter
		cSql += "		SC5.C5_NUM		= SC6.C6_NUM	AND	" + Enter
		cSql += "		SC5.C5_CLIENTE	= SC6.C6_CLI	AND	" + Enter
		cSql += "		SC5.C5_LOJACLI	= SC6.C6_LOJA	AND	" + Enter
		cSql += "		SC6.EMPRESA		= SC9.EMPRESA  		AND " + Enter	
		cSql += "		SC5.C5_NUM		= SC9.C9_PEDIDO		AND " + Enter
		cSql += "		SC5.C5_CLIENTE	= SC9.C9_CLIENTE	AND " + Enter
		cSql += "		SC5.C5_LOJACLI	= SC9.C9_LOJA		AND " + Enter
		cSql += "		SC6.C6_NUM		= SC9.C9_PEDIDO 	AND	" + Enter
		cSql += "		SC6.C6_PRODUTO	= SC9.C9_PRODUTO	AND	" + Enter
		cSql += "		SC6.C6_ITEM		= SC9.C9_ITEM		AND	" + Enter
		cSql += "		SC6.F4_ESTOQUE  = 'S'				AND " + Enter
		cSql += "		SC9.C9_PRODUTO	= SB1.B1_COD	AND " + Enter
		cSql += "		SC9.C9_NFISCAL	= '' AND " + Enter
		cSql += "		SC9.C9_BLEST	= '' AND " + Enter
		cSql += "		SC9.C9_BLCRED	= '' AND " + Enter
		cSql += "		(SC9.C9_GRUPO	= 'PA' OR (SUBSTRING(SC9.C9_GRUPO,1,3) = '216' AND SC9.C9_LOCAL = '05'))  	AND " + Enter    
		cSql += "		SC5.C5_YCLIORI	= SA1.A1_COD		AND  " + Enter
		cSql += "		SC5.C5_YLOJORI	= SA1.A1_LOJA		AND  " + Enter
		cSql += "		SC5.C5_VEND1	= SA3.A3_COD		AND " + Enter
		cSql += "		SC5.C5_TRANSP	= SA4.A4_COD		AND " + Enter
		cSql += "		SC5.C5_TRANSP	= '"+S_TRAB->A4_COD+"' 		AND " + Enter //Transportadora	
		cSql += "		SA1.D_E_L_E_T_	= '' AND " + Enter
		cSql += "		SA3.D_E_L_E_T_	= '' AND " + Enter
		cSql += "		SA4.D_E_L_E_T_	= '' AND " + Enter
		cSql += "		SB1.D_E_L_E_T_	= ''  " + Enter
		cSql += "		) TTT 	" + Enter
		cSql += " WHERE SUBSTRING(SIT,1,1) NOT IN ('1','2','3','9') 		" + Enter
		cSql += " AND ((C6_YDTNECE <> '' AND DIAS >= -7) OR C6_YDTNECE = '') " + Enter

		cSql += "GROUP BY EMPRESA, A4_COD, A4_NOME, A4_TEL, A3_COD, A3_NOME, A3_NREDUZ, A3_TEL, A1_COD, A1_NOME, A1_CGC, A1_TEL, A1_BAIRRO, A1_MUN, A1_EST, A1_CEP, C5_NUM, C6_PRODUTO, C6_ENTREG, C6_YDTNECE, C5_YPC " + Enter
		cSql += "ORDER BY A4_COD, A3_COD, A1_EST, A1_MUN, A1_NOME " + Enter

		IF CHKFILE("_TRAB_AUX")
			DBSELECTAREA("_TRAB_AUX")
			DBCLOSEAREA()
		ENDIF

		TCQUERY CSQL ALIAS "_TRAB_AUX" NEW
		DBSELECTAREA("_TRAB_AUX")
		DBGOTOP()

		NTOTAL_GERAL 	:= 0
		NTOTGER_PRAZO	:= 0
		NTOTAL_DIA		:= 0
		NTOTAL_QUAN		:= 0
		C_HTML := ""

		IF ! _TRAB_AUX->(EOF())

			IF ALLTRIM(CEMAIL) <> ""
				C_HTML := '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> '
				C_HTML += '<html xmlns="http://www.w3.org/1999/xhtml"> '
				C_HTML += '<head> '
				C_HTML += '<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" /> '
				C_HTML += '<title>Untitled Document</title> '
				C_HTML += '<style type="text/css"> '
				C_HTML += '<!-- '
				C_HTML += '.style12 {font-size: 9px; } '
				C_HTML += '.style18 {font-size: 10} '
				C_HTML += '.style21 {color: #FFFFFF; font-size: 9px; } '
				C_HTML += '.style22 { '
				C_HTML += '	font-size: 10pt; '
				C_HTML += '	font-weight: bold; '
				C_HTML += '} '
				C_HTML += '.style35 {font-size: 10pt; } '
				C_HTML += '.style36 {font-size: 9pt; } '
				C_HTML += '.style39 {font-size: 12pt; } '
				C_HTML += '.style41 { '
				C_HTML += '			font-size: 12px; '
				C_HTML += '			font-weight: bold; '
				C_HTML += '			} '
				C_HTML += '--> '
				C_HTML += '</style> '
				C_HTML += '</head> '
				C_HTML += ' '

				C_HTML += '<table width="1021" border="1"> '
				C_HTML += '  <tr> '
				C_HTML += '    <th width="751" rowspan="3" scope="col"> RELA&Ccedil;&Atilde;O PESO DISPON&Iacute;VEL POR TRANSPORTADORA </th> '
				C_HTML += '    <td width="189" class="style12"><div align="right"> DATA EMISS√O: '+ dtoC(DDATABASE) +' </div></td> '
				C_HTML += '  </tr> '
				C_HTML += '  <tr> '
				C_HTML += '    <td class="style12"><div align="right">HORA DA EMISS&Atilde;O: '+SUBS(TIME(),1,8)+' </div></td> '
				C_HTML += '  </tr> '
				C_HTML += '  <tr> '
				IF CEMPANT = "01"
					C_HTML += '    <td><div align="center" class="style41"> BIANCOGRES CER¬MICA SA </div></td> ' 
				ELSEIF CEMPANT = "05"
					C_HTML += '    <td><div align="center" class="style41"> INCESA CERAMICA LTDA </div></td> '
				ELSEIF CEMPANT = "13"
					C_HTML += '    <td><div align="center" class="style41"> MUNDI LOGISTICA LTDA </div></td> ' 
				END IF
				C_HTML += '  </tr> '
				C_HTML += '</table>		 '

				C_HTML += '<table width="1021" border="1"> '

				// TRANSPORTADORA
				C_HTML += '  <tr bgcolor="#FFFFFF"> '
				C_HTML += '    <th colspan="12" scope="col"><div align="left" class="style22">Transportadora: '+ _TRAB_AUX->A4_COD +' - '+ _TRAB_AUX->A4_NOME +' - Tel: '+ _TRAB_AUX->A4_TEL +' </div></th> '
				C_HTML += '  </tr> '

				// CABECALHO
				C_HTML += '  <tr bgcolor="#0066CC"> '

				C_HTML += '    <th width="18"	scope="col"><span class="style21"> Lc </span></th> '       
				C_HTML += '    <th width="300"	scope="col"><span class="style21"> Cliente </span></th> '
				C_HTML += '    <th width="80" 	scope="col"><div align="center"><span class="style21"> CNPJ </span></th> '
				C_HTML += '    <th width="130" 	scope="col"><span class="style21"> Cidade </span></th> '
				C_HTML += '    <th width="104"	scope="col"><span class="style21"> Bairro </span></th> '
				C_HTML += '    <th width="17" 	scope="col"><span class="style21"> UF </span></th> '
				C_HTML += '    <th width="60" 	scope="col"><span class="style21"> CEP </span></th> '

				C_HTML += '    <th width="60" 	scope="col"><div align="center"><span class="style21"> Pedido </span></th> '
				C_HTML += '    <th width="250" 	scope="col"><div align="center"><span class="style21"> Produto </span></th> '			
				C_HTML += '    <th width="60" 	scope="col"><div align="center"><span class="style21"> OC </span></th> '

				C_HTML += '    <th width="63" 	scope="col"><span class="style21"> Dt. Prev. Entrega </span></th> '
				C_HTML += '    <th width="63" 	scope="col"><span class="style21"> Peso Bruto </span></th> '			
				C_HTML += '    <th width="48" 	scope="col"><span class="style21"> Dias Empenho</span></th> '

				C_HTML += '  </tr> '

				S_VEND 		:= ""
				NTOTAL_VEN	:= 0
				NTOTVEN_PRAZO := 0
				NTOT_DIAS 	:= 0
				NQUANT 		:= 0
				DO WHILE ! _TRAB_AUX->(EOF())
					// VENDEDOR
					IF S_VEND <> _TRAB_AUX->A3_COD
						S_VEND := _TRAB_AUX->A3_COD
						IF NTOTAL_VEN <> 0
							C_HTML += '  <tr> '
							C_HTML += '    <td colspan="8" class="style18"><span class="style22">Total por Vendedor: '+SS_VEND +' </span></td> '
							C_HTML += '    <td class="style35"> <div align="right">  </div></td> '        
							C_HTML += '    <td class="style35"> <div align="right">  </div></td> '						
							C_HTML += '    <td class="style35"> <div align="right"> '+TRANSFORM(NTOTVEN_PRAZO		,"@E 999,999,999")+' </div></td> '
							C_HTML += '    <td class="style35"> <div align="center"> '+TRANSFORM(NTOT_DIAS/NQUANT	,"@E 999,999,999")+' </div></td> '
							C_HTML += '  </tr> '
						END IF						

						NTOTAL_VEN := 0
						NTOTVEN_PRAZO := 0
						NTOT_DIAS := 0
						NQUANT := 0
						C_HTML += '  <tr bordercolor="#FFFFFF"> '
						C_HTML += '    <td colspan="12">&nbsp;</td> '
						C_HTML += '  </tr> '

						C_HTML += '  <tr bgcolor="#FFFFFF"> '
						C_HTML += '    <th colspan="12" scope="col"><div align="left" class="style22">Vendedor: '+_TRAB_AUX->A3_COD+' - '+ _TRAB_AUX->A3_NOME +' - '+ _TRAB_AUX->A3_NREDUZ +' </div></th> '
						C_HTML += '  </tr> '

					END IF

					C_HTML += '  <tr> '
					C_HTML += '	   <td class="style12"> '+_TRAB_AUX->EMPRESA+' </td> '
					C_HTML += '    <td class="style12"> '+_TRAB_AUX->A1_COD+' - '+_TRAB_AUX->A1_NOME+' </td> '
					C_HTML += '    <td class="style12"><div align="center">'+_TRAB_AUX->A1_CGC+' </td> '

					C_HTML += '    <td class="style12"> '+_TRAB_AUX->A1_MUN+' </td> '
					C_HTML += '    <td class="style12"> '+_TRAB_AUX->A1_BAIRRO+' </td> '
					C_HTML += '    <td class="style12"> '+_TRAB_AUX->A1_EST+' </td> '
					//CEP
					C_HTML += '    <td class="style12"> '+_TRAB_AUX->A1_CEP+' </td> '

					C_HTML += '    <td class="style12"><div align="center">'+_TRAB_AUX->C5_NUM+' </td> '
					C_HTML += '    <td class="style12"><div align="center">'+ AllTrim(_TRAB_AUX->C6_PRODUTO) + "-" + AllTrim(Posicione("SB1", 1, xFilial("SB1") + _TRAB_AUX->C6_PRODUTO, "B1_DESC")) +' </td> '				
					C_HTML += '    <td class="style12"><div align="center">'+_TRAB_AUX->C5_YPC+' </td> '

					C_HTML += '    <td class="style12"> <div align="center"> '+dtoc(stod(_TRAB_AUX->C6_ENTREG))+' </td> '
					C_HTML += '    <td class="style12"> <div align="right"> '+TRANSFORM(_TRAB_AUX->Z9_PESOBR,"@E 999,999,999")+' </td> '
					C_HTML += '    <td class="style12"> <div align="center"> '+ ALLTRIM(STR(_TRAB_AUX->DIAS))  +' </td> '
					C_HTML += '  </tr> '
					NTOTAL_VEN 		+= _TRAB_AUX->Z9_PESOBR
					NTOTAL_GERAL 	+= _TRAB_AUX->Z9_PESOBR
					NTOTVEN_PRAZO	+= _TRAB_AUX->Z9_PESOBR
					NTOTGER_PRAZO	+= _TRAB_AUX->Z9_PESOBR

					NTOT_DIAS		+= _TRAB_AUX->DIAS
					NTOTAL_DIA		+= _TRAB_AUX->DIAS
					NQUANT		++
					NTOTAL_QUAN ++

					SS_VEND 	:= _TRAB_AUX->A3_COD +' - '+ _TRAB_AUX->A3_NOME +' - '+ _TRAB_AUX->A3_NREDUZ
					SS_TRANS 	:= _TRAB_AUX->A4_COD +' - '+ _TRAB_AUX->A4_NOME +' - Tel: '+ _TRAB_AUX->A4_TEL

					DBSELECTAREA("_TRAB_AUX")
					_TRAB_AUX->(DBSKIP())
				END DO

				C_HTML += '    <td colspan="8" class="style18"><span class="style22">Total por Vendedor: '+ SS_VEND +' </span></td> '
				C_HTML += '    <td class="style35"> <div align="right">  </div></td> '
				C_HTML += '    <td class="style35"> <div align="right">  </div></td> '			
				C_HTML += '    <td class="style35"> <div align="right"> '+TRANSFORM(NTOTVEN_PRAZO,"@E 999,999,999")+' </div></td> '
				C_HTML += '    <td class="style35"> <div align="center"> '+TRANSFORM(NTOT_DIAS/NQUANT	,"@E 999,999,999")+' </div></td> '
				C_HTML += '  </tr> '					

				C_HTML += '  <tr bordercolor="#FFFFFF" class="style18"> '
				C_HTML += '    <td colspan="12" class="style36">&nbsp;</td> '
				C_HTML += '  </tr> '
				C_HTML += '  <tr bgcolor="#FFFFFF"> '
				C_HTML += '    <th colspan="8" scope="col"><div align="left" class="style35">Total <strong>por</strong> Transportadora: '+ SS_TRANS +' </div></th> '
				C_HTML += '    <td class="style35"> <div align="right">  </div></td> '
				C_HTML += '    <td class="style35"> <div align="right">  </div></td> '			
				C_HTML += '    <td class="style35"> <div align="right"> '+TRANSFORM(NTOTGER_PRAZO	,"@E 999,999,999")+' </div></td> '
				C_HTML += '    <td class="style35"> <div align="center"> '+TRANSFORM(NTOTAL_DIA /NTOTAL_QUAN	,"@E 999,999,999")+' </div></td> '
				C_HTML += '  </tr> '

				C_HTML += '  <tr bordercolor="#FFFFFF" class="style18"> '
				C_HTML += '    <td colspan="12" class="style12">&nbsp;</td> '
				C_HTML += '  </tr> '
				C_HTML += '</table> '
				C_HTML += 'Esta È uma mensagem autom·tica, favor n„o responde-la.'
				C_HTML += '</body> '
				C_HTML += '</html> '
				COMIS_EMAIL()
			ELSE
				CCC_TEXTO += 'EMAIL N√O CADASTRADO NA TRANSPORTADORA: ' + CCODIGO +' - '+ CNOME + Enter
			END IF
		END IF
		DBSELECTAREA("S_TRAB")
		S_TRAB->(DBSKIP())
	END DO

	IF ALLTRIM(CCC_TEXTO) <> ""
		EMA_N_CADAS(CCC_TEXTO)
	END IF

RETURN

/*
‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
≤±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±≤
≤±±…ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÀÕÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÀÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÕÕª±±≤
≤±±∫ COMIS_EMAIL         ∫Autor  ≥ MADALENO           ∫ Data ≥  26/06/07   ∫±±≤
≤±±ÃÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ ÕÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ ÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕÕπ±±≤
≤±±∫Desc.       ROTINA PARA GERAR O EMAIL E ENVIAR O MESMO                 ∫±±≤
≤±±∫                                                                       ∫±±≤
≤±±»ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕº±±≤
≤±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±≤
ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
*/
STATIC FUNCTION COMIS_EMAIL()

	Local lOk

	IF CEMPANT == "01"
		cRecebe		:= CEMAIL
		cRecebeCC	:= "" 
		cAssunto	:= 'BIANCOGRES - Relacao Peso Disponivel por Transportadora '
	ELSEIF CEMPANT = "05"
		cRecebe		:= CEMAIL
		cRecebeCC	:= "" 
		cAssunto	:= 'INCESA - Relacao Peso Disponivel por Transportadora '
	ELSEIF CEMPANT = "13"
		cRecebe		:= CEMAIL
		cRecebeCC	:= "paloma.santos@biancogres.com.br" 
		cAssunto	:= 'MUNDI - Relacao Peso Disponivel por Transportadora '
	ENDIF

	If lDebugWF
		cRecebe := "pablo.nascimento@biancogres.com.br"
		cRecebeCC := ""
	EndIf

	lOk := U_BIAEnvMail(,cRecebe,cAssunto,C_HTML,,,.F.,cRecebeCC)
	
	IF !lOK
		EMA_N_CADAS("EMAIL INV¡LIDO: " + _TRAB_AUX->A4_COD +' - '+ _TRAB_AUX->A4_NOME + ' - ' + CEMAIL )
	ENDIF

	C_HTML := ""
RETURN


/*
‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
≤±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±≤
≤±±…ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÀÕÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÀÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÕÕª±±≤
≤±±∫ EMA_N_CADAS         ∫Autor  ≥ MADALENO           ∫ Data ≥  26/06/07   ∫±±≤
≤±±ÃÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ ÕÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ ÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕÕπ±±≤
≤±±∫Desc.       ROTINA PARA GERAR O EMAIL PARA CLAUDEIR QUANDO O EMAIL     ∫±±≤
≤±±∫            DER ERRO.                                                  ∫±±≤
≤±±»ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕº±±≤
≤±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±≤
ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
*/
STATIC FUNCTION EMA_N_CADAS(CCMENSAGEM)  

	IF CEMPANT == "01"
		cRecebe		:= "geraldo.santos@biancogres.com.br" 
		cRecebeCC	:= ""
	ELSE
		cRecebe		:= "ana.silva@biancogres.com.br" 
		cRecebeCC	:= ""
	END IF

	cAssunto	:= 'EMAIL N√O ENVIADOS PARA TRANSPORTADORA: ' //+ CCODIGO +' - '+ CNOME

	If lDebugWF
		cRecebe := "tiago@facilesistemas.com.br"
		cRecebeCC := ""
	EndIf

	U_BIAEnvMail(,cRecebe,cAssunto,CCMENSAGEM,,,.F.,cRecebeCC)

RETURN