CREATE TABLE VNINTEGRACAO_PEDIDO_CABEC (
	emp_fil varchar(4) DEFAULT ('    '),
	id int DEFAULT ((0)),
	uuid varchar(36) DEFAULT ('                                    '),
	req_id varchar(255) DEFAULT (' '),
	legacy_code varchar(255) DEFAULT (' '),
	customer_uuid varchar(36) DEFAULT ('                                    '),
	customer_code varchar(6) DEFAULT ('      '),
	customer_store varchar(2) DEFAULT ('  '),
	payment_method_uuid varchar(36) DEFAULT ('                                    '),
	payment_code varchar(3) DEFAULT ('   '),
	total_sale_value float DEFAULT ((0)),
	freight_type varchar(10) DEFAULT ('          '),
	ipi_value float DEFAULT ((0)),
	gross_value float DEFAULT ((0)),
	net_value float DEFAULT ((0)),
	discount_value float DEFAULT ((0)),
	discount_percentage float DEFAULT ((0)),
	interest_value float DEFAULT ((0)),
	interest_percentage float DEFAULT ((0)),
	gross_weight float DEFAULT ((0)),
	net_weight float DEFAULT ((0)),
	observation varchar(255) DEFAULT (' '),
	deadline int DEFAULT ((0)),
	status_code int DEFAULT ((0)),
	created_at datetime NULL,
	freight_value float DEFAULT ((0)),
	freight_table_uuid varchar(36) DEFAULT ('                                    '),
	timestamp_import datetime NULL,
	timestamp_integrated datetime NULL,
	status_integrated varchar(1) DEFAULT (' '),
	pedido_protheus varchar(6) DEFAULT ('      '),
	error_integrated varchar(255) DEFAULT (' ')
);


CREATE TABLE VNINTEGRACAO_PEDIDO_ITENS (
	emp_fil varchar(4) DEFAULT ('    '),
	id int DEFAULT ((0)),
	uuid varchar(36) DEFAULT ('                                    '),
	req_id varchar(255) DEFAULT (' '),
	legacy_code varchar(255) DEFAULT (' '),	
	order_uuid varchar(36) DEFAULT ('                                    '),
	product_uuid varchar(36) DEFAULT ('                                    '),
	product_code varchar(15) DEFAULT ('               '),
	price_list_uuid varchar(36) DEFAULT ('                                    '),
	quantity float DEFAULT ((0)),
	unitary_gross_value float DEFAULT ((0)),
	unitary_net_value float DEFAULT ((0)),
	unitary_ipi_value float DEFAULT ((0)),
	unitary_discount_value float DEFAULT ((0)),
	unitary_gross_weight float DEFAULT ((0)),
	unitary_net_weight float DEFAULT ((0)),
	total_gross_value float DEFAULT ((0)),
	total_net_value float DEFAULT ((0)),
	total_discount_value float DEFAULT ((0)),
	total_gross_weight float DEFAULT ((0)),
	total_ipi_value float DEFAULT ((0)),
	total_net_weight float DEFAULT ((0)),
	ipi_percentage float DEFAULT ((0)),
	discount_percentage float DEFAULT ((0)),
	deadline int DEFAULT ((0)),
	created_at datetime NULL,
	is_pallet varchar(1) DEFAULT (' ')
);