IF
(
    SELECT OBJECT_ID('[dbo].[facin_Produtos]')
) > 0
    DROP VIEW [dbo].[facin_Produtos];
GO

CREATE VIEW [dbo].[facin_Produtos]
AS


  SELECT TOP 6000
    B1_COD AS CODIGO,
    SB1.B1_DESC AS DESCRIC,
    SA2.A2_NREDUZ AS FABRIC,
    SB1.B1_PESBRU AS PESBRUTO,
    SB1.B1_PESO AS PESO,
    AIB.AIB_PRCCOM AS PRCVENDA,
    SB1.B1_UM AS UNIDMED,
    SB1.B1_GRUPO AS GRUPO,
    SB1.B1_MSBLQL AS BLOQUEADO,
    SB1.D_E_L_E_T_ AS DELETED,
    SB2.B2_QATU AS SALDO,
    B1_USERLGI,
    B1_USERLGA,
    B2_USERLGI,
    B2_USERLGA,
    B1_COD
  FROM SB1010 SB1
    JOIN SA2010 SA2
    ON SA2.A2_FILIAL = ''
      AND SA2.A2_COD = SB1.B1_PROC
      AND SA2.A2_LOJA = SB1.B1_LOJPROC
      AND SA2.D_E_L_E_T_ = ''
    JOIN AIB010 AIB
    ON AIB.AIB_FILIAL = ''
      AND AIB.AIB_CODFOR = SB1.B1_PROC
      AND AIB.AIB_LOJFOR = SB1.B1_LOJPROC
      AND AIB.AIB_CODTAB = '001'
      AND AIB.AIB_CODPRO = SB1.B1_COD
      AND AIB.D_E_L_E_T_ = ''
    JOIN SB2010 SB2
    ON SB2.B2_FILIAL = 'AAPES004'
      AND SB2.B2_COD = SB1.B1_COD
      AND SB2.B2_LOCAL = '01'
      AND SB2.B2_QATU > 0
  WHERE SB1.B1_FILIAL = ''
