IF
(
    SELECT OBJECT_ID('[dbo].[facin_Clientes]')
) > 0
    DROP VIEW [dbo].[facin_Clientes];
GO

CREATE VIEW [dbo].[facin_Clientes]
AS
  SELECT TOP 6000
    A1_COD + '-' + A1_LOJA AS CODIGO,
    A1_NOME AS RAZAOSOCIA,
    A1_NREDUZ AS FANTASIA,
    A1_PESSOA AS PESSOA,
    A1_CGC AS CPFCNPJ,
    A1_EMAIL AS EMAIL,
    A1_CEP AS CEP,
    A1_END AS ENDEREC,
    A1_NUMRA AS NUMERO,
    A1_COMPLEM AS COMPLEM,
    A1_BAIRRO AS BAIRRO,
    A1_INSCR AS INSCESTAD,
    A1_DDD AS DDD,
    A1_TEL AS TELEFONE,
    A1_FAX AS FAX,
    A1_LC AS LIMCRED,
    A1_VENCLC AS VENCCREDIT,
    A1_VEND AS VENDEDOR,
    A1_COD_MUN AS CODMUNIC,
    A1_EST AS UF,
    A1_MSBLQL AS BLOQUEADO,
    D_E_L_E_T_ AS DELETED,
    SA1.R_E_C_N_O_ AS RECNO,
    A1_USERLGI,
    A1_USERLGA,
    A1_COD,
    A1_LOJA
  FROM SA1010 SA1
  WHERE SA1.A1_FILIAL = ''
    AND EXISTS
(
    SELECT NULL
    FROM SF2010 SF2
    WHERE SF2.F2_CLIENTE = SA1.A1_COD
      AND SF2.F2_LOJA = SA1.A1_LOJA
      AND SF2.D_E_L_E_T_ = ''
);
